### ISSUE TITLE
jail.local Fail2Ban rules deleted upon update/maintenance

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#1064]
I have some Fail2Ban rules such as whitelisting my personal OpenVPN from my devices from tripping filters, and automatically reporting to blocklist.de as I have an account and like to contribute to their communal blocklist, as well as automated reporting. What steps may I take to prevent this from happening on each update? What steps can we take to help others from keeping that happening. Because all of my personal devices only really come through one IP address which is my VPN

**Comment by yodax** [comment]
This happens because of [line 309](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/system.sh#L309) in setup/system.sh. The reasoning behind it is that we previously used that file to setup fail2ban. If we wouldn't delete it, it might contain an old incompatible configuration that would conflict with the new one in jail.d/mailinabox.conf.

See my comment in https://github.com/mail-in-a-box/mailinabox/pull/798 on 14 Apr 2016.

> Should we do this in the upgrade script? Then we do this only once, if a user then tries to add something to jail.local it won't be removed.

We never got to a solution.

Initially I thought we could remove the line in a version or 2, but I found (see ownCloud issues) that people often skip many versions.

So if anyone has a good idea to tackle this, I would love the input!

**Comment by anoma** [comment]
You can also use conf files in  `/etc/fail2ban/jail.d/ ` as a third and FORTH set of jail files which are not deleted etc

This is very badly documented but is well summarised here (https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-centos-7) as 

    /etc/fail2ban/jail.conf
    /etc/fail2ban/jail.d/*.conf, alphabetically
    /etc/fail2ban/jail.local
    /etc/fail2ban/jail.d/*.local, alphabetically

So the way I had been thinking about it is 

    jail.conf for Ubuntu
    jail.local for MIAB
    /etc/fail2ban/jail.d/*.conf for end users

however it might be better just using `/etc/fail2ban/jail.d/*.conf,` for MIAB allowing the flexibility of using using many files but still leaving an overide option for end users with .local variants

e.g.

    /etc/fail2ban/jail.conf  << Ubuntu
    /etc/fail2ban/jail.d/*.conf, alphabetically  << MIAB
    /etc/fail2ban/jail.local << no one
    /etc/fail2ban/jail.d/*.local, alphabetically <<< end user

To move to this we should perhaps put a warning in system status when it detects local changes and point at a summary of what to do before upgrading?

**Comment by yodax** [comment]
We put the MIAB one in jail.d (, if i'm not mistaken at your request :smile:). 

When looking at the original PR I looked into detecting the changes, but we added the IP in dynamically. So it would be tricky to do. (Not impossible)

I agree that putting extra user jails in jail.d would make sense. It would be nice if we could stop deleting the jail.local file since for the new version we don't need it. It's just there to not break older upgrades.

**Comment by anoma** [comment]
Yeah I have got myself turned around here flipping between testing stock, post .d change and my rolling security tests.

I think we are on the right route here as this is not complicated it just very badly documented (which is something we could easily do for MIAB) specific users.

**Comment by ChiefGyk** [comment]
So if I make a file in jail.d with my custom tweaks I should be fine? I will test and see
