### ISSUE TITLE
ownCloud Contacts - Web Interface

### ISSUE THREAD

**Issue by henningwerner** [mail-in-a-box/mailinabox#1075]
I only see the loading animation, and on the right site something like "No contacts available".

Furthermore CardDav does not seem to work.
But ActiveSync seems to work.

**Comment by MariusBluem** [comment]
Please try to create a new adressbook, by clicking on "Settings" in the contatcs-app and typing in a name for your new CardDAV-adressbook ... Seems that the non-ending-load is happening, because you have currently no adressbooks for whatever reason 😁 

![bildschirmfoto 2017-01-21 um 12 41 13](https://cloud.githubusercontent.com/assets/19711361/22174154/24218a90-dfd7-11e6-9508-37a3ba76afb4.png)

Please report back 👊 

Greetings
Marius from the Nextcloud community

**Comment by henningwerner** [comment]
Thanks for your fast reply 👍 

But this should be curious, because ActiveSync contacts info's are already come from OwnCloud too?

Side question, why not make pull requests for an Nextcloud integration?

**Comment by MariusBluem** [comment]
> But this should be curious, because ActiveSync contacts info's are already come from OwnCloud too?

So ActiveSync is working - and CardDAV too? The only non-working thing is the contacts-app. You are also seeing the adressbook in the Settings (see guide above)?

> Side question, why not make pull requests for a Nextcloud integration?

Please see the long and sadly never ending discussion over here: #514 ... 

Greetings
Marius from the Nextcloud community

**Comment by henningwerner** [comment]
![image](https://cloud.githubusercontent.com/assets/7737790/22175805/f5b88dc2-dffc-11e6-86fa-f51c330d80fd.png)

Have a look here.
I definitely had an Contact book and this already get synced with my ActiveSync Devices.
Only CardDav wouldn't work for me...

**Comment by MariusBluem** [comment]
Could you please try to create a new adressbook in your Instance - reload the page - and try to create new contacts 😁 Would be interesting, whether this is working 😅 

Greetings
Marius from the Nextcloud community
