### ISSUE TITLE
Strange Log

### ISSUE THREAD

**Issue by arobase13** [mail-in-a-box/mailinabox#1130]
Hello, to track a cron spot on my server using mailinabox, I have login and disconnect to ip addresses, which I do not know, hacking?

> 
Apr  2 08:57:21 mail postfix/smtpd[9850]: connect from unknown[190.124.250.39]
Apr  2 08:57:22 mail postfix/smtpd[9850]: disconnect from unknown[190.124.250.39]

Thank you in advance for your help.

Edit : 

> 
Apr  2 09:08:51 mail postfix/smtpd[10888]: connect from mail.metex.com.my[175.139.178.198]
Apr  2 09:08:52 mail postfix/smtpd[10888]: disconnect from mail.metex.com.my[175.139.178.198]

> 
Apr  2 09:12:14 mail kernel: [67516.307810] [UFW BLOCK] IN=eth0 OUT= MAC=58:c2:8e:88:09:d2:10:f3:11:11:00:8a:08:00 SRC=104.236.183.22 DST=myip LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=54321 PROTO=TCP SPT=60604 DPT=5093 WINDOW=65535 RES=0x00 SYN URGP=0
Apr  2 09:12:34 mail named[1200]: error (unexpected RCODE REFUSED) resolving 'NS2.ENTELNET.BO/A/IN': 168.205.99.70#53
Apr  2 09:12:34 mail named[1200]: error (unexpected RCODE REFUSED) resolving 'NS.ENTELNET.BO/A/IN': 168.205.99.70#53
Apr  2 09:12:35 mail postfix/smtpd[11352]: connect from unknown[200.87.52.4]
Apr  2 09:12:35 mail postfix/smtpd[11352]: disconnect from unknown[200.87.52.4]

Question, is fail2ban active by default in mailinabox?

**Comment by yeah** [comment]
> Question, is fail2ban active by default in mailinabox?

Yes.

**Comment by arobase13** [comment]
Indeed after checking a lot of idiots have been banned for attempts to connect in SSH. On the other hand I see that there are attempts to connect to smtpd but there on the other hand I do not see any banishment there is a specific setting to do?

**Comment by adamvallee** [comment]
Hey arobase13,

Just a quick check and 190.124.250.39 is a known spammer (http://bgp.he.net/ip/190.124.250.39#_rbl) . The IP address originates from RACK LODGE in Costa Rica, (http://bgp.he.net/AS28110)  you are not likely to make any headway with their abuse team.

You are running a mail server, unfortunately you will have a great deal of attempts.
I have even attempted to obfuscate my mx server, by not following the naming convention implemented by josh (box.domain.tld) for example using "er.e2p.domain.tld" or some such sub-domain to make it harder to guess my mx server.

Anyway this did nothing to resolve the issues, because these "people" just do large scale mx lookups on domain names (new or old - my domain was registered in 1998) and then just make attempts against any mx server they find.

Anyway, it seems as though your MIAB is working as it should. 

Adam

**Comment by yeah** [comment]
Guys, please use GitHub issues for development related stuff (e.g. bugs, feature requests, patches, pull requests) only. The forum at https://discourse.mailinabox.email is for general discussion, help and support with MIAB.

Keeping these things separated helps the developers focus on making MIAB better instead of having to go through tons of issues that have nothing to do with MIAB development. Thanks!

**Comment by arobase13** [comment]
ok
