### ISSUE TITLE
Add Minio backup support

### ISSUE THREAD

**Issue by OmgImAlexis** [mail-in-a-box/mailinabox#1148]
Since this already supports s3 this would be trivial to add as [minio](https://github.com/minio/minio) is a drop in replacement for s3. All that would need to be added is another dropdown on the backups page with exactly the same options as s3 but with the bucket region set to `us-east-1` and an optional box for the endpoint url.

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/mail-in-a-box/mailinabox/issues/717

**Comment by damongant** [comment]
Been looking into hacking this into my instance - not as easy as backup.py runs a reduce over the regions baked into boto. Maybe this could be done over the config file (for which a path is already being set in fix_boto)

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/minio/minio/issues/1025

**Comment by JoshData** [comment]
Let's take this to #717.

**Comment by mkohns** [comment]
I write this how-to for people you want to use min.io as a backup storage for miab.

The problem: Current AWS S3 integration uses boto v2 library. This is not working correctly with minio. The bucket.list call does not response in the expected format when connected to minio.

The solution: update miab to boto v3 library.

**Step 1**: install boto3 into virtual env:
`sudo /usr/local/lib/mailinabox/env/bin/pip install boto3`

**Step 2**: backup your orginal backup.py script
```
cd
sudo mv mailinabox/management/backup.py mailinabox/management/backup.org
```
**Step 3**: modify backup.org to work with minio. Duplicity works out of the box with minio, only the list_target_files functions need to be adjusted in order to make it work. This function is used to verify that the config is okay.
Goto `def list_target_files(config):`
Search for: `elif target.scheme == "s3":`
Uncomment the whole block and replace it with:

```
        elif target.scheme == "s3":
                host = "https://" + target.netloc
                bucket = target.path[1:].split('/')[0]
                path = '/'.join(target.path[1:].split('/')[1:]) + '/'

                if path == '/':
                        path = ''

                if bucket == "":
                        raise ValueError("Enter an S3 bucket name.")

                # connect to the region & bucket
                import boto3
                from botocore.client import Config
                try:
                      s3 = boto3.client('s3',endpoint_url=host,aws_access_key_id=config["target_user"],aws_secret_access_key=config["target_pass"],config=Config(signature_version='s3v4'),region_name='us-east-1')
                      response_contents = s3.list_objects_v2(Bucket=bucket).get('Contents')

                except botocore.exceptions.ClientError as e:
                        raise ValueError(e)

                if response_contents is None:
                        return []

                return [(key['Key'], key['Size']) for key in response_contents]

        else:
                raise ValueError(config["target"])

```
