### ISSUE TITLE
Use my own DNS without giving it to mailinabox

### ISSUE THREAD

**Issue by herohamp** [mail-in-a-box/mailinabox#1235]
Can I use my own DNS service like cloudflare with mailinabox. I don't want to set it to my nameserver

**Comment by yodax** [comment]
Yes there is a page after the install that tells you how to configure the external server. Not all servers work the same and some don't support the record types. I do believe (if I recall correctly) that some people use cloudfare.

**Comment by Gatewayy** [comment]
I use it with all of my MIAB domains without issue.  The A record that you point at you MIAB at will need to have cloudflare's proxy disabled (grey cloud over orange cloud) as they only allow ports 80 and 443 through.

**Comment by chamunks** [comment]
CloudFlare is very particularly dedicated to keeping up to date with standards and records.  This is likely going to be a popular choice because if your DNS goes offline your whole operation goes down.  If your email goes down it either tries again or it bounces.  Either way, your whole project doesn't completely disappear.

**Comment by JoshData** [comment]
Closing since the original question was answered.
