### ISSUE TITLE
Tor hidden service deployment

### ISSUE THREAD

**Issue by cmars** [mail-in-a-box/mailinabox#1291]
I'd like to expose the web interface as a Tor hidden service in stealth mode with HidServAuth on the clients.

Why would I want to do such a thing?

1. Reduce the attack surface. I don't really have a use for general public internet access to the web console. I'm the only one who uses it. mailinabox only really needs a public internet IP, DNS name and inbound ports for email protocols.
2. I'm uneasy about how easy it is to identify mailinabox installations by scanning.
3. Increased privacy. Regular network traffic to a personal email server, especially email clients that poll, is very personally-identifying.
4. Network agility. I'd like to host my mailinabox at home (that part about physical security...), but my local ISP blocks email ports aggressively. Taking this a step further, I can forward all the necessary ports mailinabox needs from an ingress cloud instance over Tor to my home server. Ingress gets a public IP, DNS name, and the TLS certificate is established there -- but the backend is the hidden service. The neat part about this: I can move my home server across networks, it could be on LTE in a camper, I don't have to change a thing, and my cloud provider never stores data-at-rest.

I've added an entry for the hidden service server_name to /etc/nginx/conf.d/local.conf as a PoC. The web interface is quite lightweight, and works well in TorBrowser!

Would you accept a patch adding support for this kind of configuration, perhaps as an option for advanced users?

**Comment by JoshData** [comment]
Hi @cmars. This is very interesting but would probably not be a good fit for a novice-friendly project like this. What's the fewest number of changes you'd need to make to Mail-in-a-Box to make it possible?

**Comment by jirislav** [comment]
IMHO it's very good that Mail-in-a-Box is novice-friendly. On the other side, many users, who initially started with MIAB as novices, learned a lot about how it works & would like to gradually upgrade their system according to their desire. But that part is harder if we keep MIAB "novice-only". Realistically speaking, it's actually "novice & expert only". No professional or intermediate.

Would be great to have some mechanism for switching Pro features on. And this issue is a Pro feature for sure. I'd love to have this implemented btw :smile:

**Comment by jirislav** [comment]
How about this prompt while installing?

![Pro features yes-no prompt](https://user-images.githubusercontent.com/7583416/33229845-a7495a4a-d1d7-11e7-9773-d85f2e7a0d0d.png)

If user selected "Yes", then it would be shown this:
![Pro features choice image](https://user-images.githubusercontent.com/7583416/33229837-7d116c04-d1d7-11e7-9b7e-e7a79cac1abd.png)

**Comment by gg2001** [comment]
Bump

**Comment by chris13524** [comment]
Unrelated to the title of this issue, I guess. But it would also be nice to have "pro features" in this system. E.g. using Mailgun as a relay (but maybe not advertised directly to be novice friendly).

**Comment by JoshData** [comment]
Closing... because no one answered my question.

**Comment by myfirstnameispaul** [comment]
I realize this issue is closed, but just in case someone goes searching for Tor issues, there are many ISPs who put in their ToS that you are not permitted to run Tor exit nodes and they can cancel your account for this activity.

My observation is most people never read ToS, so they may enable this option without understanding the ramifications.

**Comment by cmars** [comment]
This issue was not proposing running an exit node though. Hidden services only interact with the Tor network.

If your ISP cancels you just for _using Tor_, get another ISP.

**Comment by myfirstnameispaul** [comment]
> If your ISP cancels you just for using Tor, get another ISP.

Don't tell me what to do.
