### ISSUE TITLE
Thats not a valid email address error ... I need help

### ISSUE THREAD

**Issue by radicalqush** [mail-in-a-box/mailinabox#1326]
I have been trying to install mailinabox but i keep encountering errors, the first was zpushgit and i read a thread here on how to fix it, i was supposed to apply update and upgrade again...... now i am doing it all over again and its now telling me that the email me@mydomain is not valid. I need help please

**Comment by donsicilly** [comment]
I am facing the same problem...THAT IS NOT A VALID EMAIL error..

How can i fixx this?

**Comment by Gingeropolous** [comment]
I am also experiencing this problem

**Comment by starsoccer** [comment]
Also having this issue. Using the same exact email address I have on another mail in a box server.

**Comment by ali3seven** [comment]
I have the same issue. What really happen for mail in a box?
Excuse me, but every time I was going to install, face with new problem.
I don't think it can be considered good. I was wondering if a stable version release.
Could anyone kindly tell how to prevent the loop? @JoshData 
It showed that it solved [here](https://discourse.mailinabox.email/t/me-domain-ninja-not-valid-e-mail-address/448). but actually I don't think so with the latest git.
I tried with different username@domain.com, also not any special characters were used. However the issue is existed. 
Thanks

**Comment by JoshData** [comment]
This issue will be fixed in the next release. The master branch should work now (at least as far as this issue goes).

> Excuse me, but every time I was going to install, face with new problem. I don't think it can be considered good.

This is an open source project so please feel free to jump in where help is needed and make it better!
