### ISSUE TITLE
Unable to renew Let's Encrypt cert

### ISSUE THREAD

**Issue by drpain** [mail-in-a-box/mailinabox#1368]
Hi Hi,

I am getting 500 internal server errors when I try and update the certificate through the interface. Please halp!

**Comment by UjoJano** [comment]
Hello. I have same serious problem (not 500, but Unable to renew)

 Certificate renewal does not work. Certificates are expired and I can not create any new ones now.

Mailinabox v 0.26c, updated, rebooted
I have a mailinabox from 09/2017. in 12/17 SSL updated OK. In 01/12 or 02/12 I updated from 0.23 to 0.26. Today (since refresh does not work cert) I updated from 0.26 (a or b) to 0.26c
I tried:https://github.com/mail-in-a-box/mailinabox/issues/1101#issuecomment-281026627
Next I run: sudo pip3 install --upgrade pyOpenSSL
Renew:
./management/ssl_certificates.py
/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/acme/jose/jwa.py:110: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)

A TLS certificate was requested for: box. example.com, example.com, www.example.com.
We have to wait 60 seconds for the certificate to be issued...
We have to wait 50 seconds for the certificate to be issued...
We have to wait 40 seconds for the certificate to be issued...
We have to wait 30 seconds for the certificate to be issued...
We have to wait 20 seconds for the certificate to be issued...
We have to wait 10 seconds for the certificate to be issued...
Traceback (most recent call last):
  File "./ssl_certificates.py", line 803, in <module>
    provision_certificates_cmdline()
  File "./ssl_certificates.py", line 446, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "./ssl_certificates.py", line 331, in provision_certificates
    logger=my_logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 64, in issue_certificate
    agree_to_tos_url, validation_method, acme_server, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 121, in validate_domain_ownership
    challg = submit_domain_validation(client, regr, account, challenges_file, domain, validation_method, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 433, in submit_domain_validation
    message = '; '.join(c.error.detail for c in challg.challenges if c.status.name == "invalid")
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 433, in <genexpr>
    message = '; '.join(c.error.detail for c in challg.challenges if c.status.name == "invalid")
AttributeError: 'NoneType' object has no attribute 'detail'

How to solve it?

Can I downgrade to the version of 0.23?

**Comment by UjoJano** [comment]
Nobody can help me?

**Comment by UjoJano** [comment]
It can be closed. Solved.

**Comment by UjoJano** [comment]
The problem was with ipv6. I remove IPv6 record from DNS, and my hosting manager removed an ipv6 requisition from mailinabox.conf

**Comment by tjbenator** [comment]
I'm having the same issue. I tried upgrading to v0.26c.

```
travis@mail:~/mailinabox$ sudo ./management/ssl_certificates.py 
/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/acme/jose/jwa.py:110: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)

A TLS certificate was requested for: mail.binarypenguin.net.
We have to wait 60 seconds for the certificate to be issued...
We have to wait 50 seconds for the certificate to be issued...
We have to wait 40 seconds for the certificate to be issued...
We have to wait 30 seconds for the certificate to be issued...
We have to wait 20 seconds for the certificate to be issued...
We have to wait 10 seconds for the certificate to be issued...
Traceback (most recent call last):
  File "./management/ssl_certificates.py", line 803, in <module>
    provision_certificates_cmdline()
  File "./management/ssl_certificates.py", line 446, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "./management/ssl_certificates.py", line 331, in provision_certificates
    logger=my_logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 64, in issue_certificate
    agree_to_tos_url, validation_method, acme_server, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 121, in validate_domain_ownership
    challg = submit_domain_validation(client, regr, account, challenges_file, domain, validation_method, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 433, in submit_domain_validation
    message = '; '.join(c.error.detail for c in challg.challenges if c.status.name == "invalid")
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 433, in <genexpr>
    message = '; '.join(c.error.detail for c in challg.challenges if c.status.name == "invalid")
AttributeError: 'NoneType' object has no attribute 'detail'
travis@mail:~/mailinabox$ 
```

**Comment by drpain** [comment]
I personally had to manually get the certificate via DNS TXT records, and symlink them to the files the application uses.

**Comment by arctic-ice-cool** [comment]
How do you resolve this? This is becoming a problem with our MiaB's and we've broken more than we've fixed from trying different hacks to get this working! :-) Anyone resolved this issue? Removing MiaB install files and even installing on a new server isn't resolving this.

Thanks!

**Comment by arctic-ice-cool** [comment]
OK so after trying loads of different things (including full re-installs and installs via git) the simple fix was to add this to the custom DNS for the hostname:

> box.miab.hostname.com  | CAA | 0 issuewild letsencrypt.org

**Comment by drpain** [comment]
Yeah seems to be a few different issues going around. Not sure how you fix all of them.

**Comment by arctic-ice-cool** [comment]
Well this is definitely an issue worth keeping open and people providing feedback all in one place so we can figure it out together.

**Comment by koztay** [comment]
I have the same problem and none of the above methods worked for me. I am using the MIAB server with expired certificates for 2 days.

**Comment by UjoJano** [comment]
Hi.

Go to /etc/mailinabox.conf and remove line:
PUBLIC_IPV6=
PRIVATE_IPV6=

(Backup this conf before change)

**Comment by martindale** [comment]
Ran into this with Ubuntu 16.04.  Unable to upgrade, LTS out of support...

**Comment by myfirstnameispaul** [comment]
You need to upgrade, which is more like a migration:

https://mailinabox.email/maintenance.html#upgrade

**Comment by martindale** [comment]
> You need to upgrade, which is more like a migration:
> 
> https://mailinabox.email/maintenance.html#upgrade

Yes, the Mailinabox upgrade fails because it requires packages which are no longer served on the Ubuntu 16.04 infrastructure (all 404).  I'm going to have to upgrade my OS before I can upgrade Mailinabox.
