### ISSUE TITLE
Suggest 0.31 with EOL countdown timer

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#1516]
I started to plan my upgrades and it occurs to me that there are two back stop dates where migrating from any old version (<=0.30) to the latest 18.04 only release may stop working

1. April 2019 EOL for Ubuntu 14.04 may bring unfixable MIAB incompatibilities
2. It is impractical for MIAB to keep maintaining fixes for 14.04 for ever

The reality is probably not this bleak or tight for time but there is no doubt there will come a point where upgrades may not work or at the very least may not be properly tested any longer.

Regardless it makes sense to in advance draw a line where < 0.40 is no longer supported or, due to human nature, we will get issues and horror storys for a long time.

So I suggest 0.31 is released with a GUI countdown timer and/or a weekly admin email prompting users to upgrade ASAP.

**Comment by alento-group** [comment]
Well 0.40 is released now.  0.40 will automatically update to v 0.30 if setup is run on a Ubuntu 14.04 machine.  Are you suggesting that any further updates to packages for Ubuntu 14.04 between the release date of 0.40 and EoL in April may break MiaB v0.30?  If that were to happen I would imagine that there would be no choice but to release a v 0.31.  However, I am hopeful that won't happen.  I do imagine that when the repositories are moved by Canonical this will become an issue though ... so at that time the install script will either need to refer to the correct repositories for EoL versions of Ubuntu so that older boxes can still be upgraded (by releasing a v 0.31) OR people will need to be told, sorry about your luck.

Ok, so the question that you are really asking is will we support those people who fail to upgrade by the EoL date from 14.04 to 18.04.


(I hope I remember to come back and rewrite this when I am more awake!)

**Comment by JoshData** [comment]
I don't intend to do any further work for Ubuntu 14.,04. That could change depending on circumstances. But it's fair to say that Mail-in-a-Box support for Ubuntu 14.04 has ended.

I don't see a reason to have an update for 14.04 because if people know that there's a 14.04 update, then they also probably know there's an 18.04 version....

**Comment by anoma** [comment]
YMMV but my experience of this type of upgrade is that more users that we will be comfortable with will not even know that their system is EOL until after well after it is EOL.

I am running an EOL install myself now as since I assumed I have until April.

Thanks for the clarification.

**Comment by JoshData** [comment]
We can deal with that when it happens. :)
