### ISSUE TITLE
LastPass always says admin login form is insecure

### ISSUE THREAD

**Issue by binarykitchen** [mail-in-a-box/mailinabox#1549]
My password manager LastPass complains. Tells it's insecure which doesn't look good, even more confusing when all is over HTTPS>

I think it's because the `<form>` element of your login form has the type missing. Known issue if you research.

**Comment by JoshData** [comment]
Just for reference, since the form is handled by AJAX, the type doesn't matter, functionality-wise.

But I'd be glad to merge a PR that puts in a type that LastPass will like.

**Comment by cmharper** [comment]
@binarykitchen These links may be of some help with your pull request:
https://forums.lastpass.com/viewtopic.php?f=12&t=246685
https://forums.lastpass.com/viewtopic.php?f=7&t=261595
https://lastpass.com/support.php?cmd=showfaq&id=7336

I do not use LastPass so cannot verify this but I would hazard a guess that the alert you are seeing is because none of the form tags in management/templates/login.html, management/templates/users.html, management/templates/system-backup.html, management/templates/aliases.html and management/templates/custom-dns.html specify the "method" (or possibly "type" as you suggested) attribute.  As far as I am aware the method (or type) attribute is not mandatory for HTML (see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form)).

**Comment by binarykitchen** [comment]
Ok, here is the PR to add the missing form method
https://github.com/mail-in-a-box/mailinabox/pull/1565

**Comment by robjloranger** [comment]
close as merged?

**Comment by JoshData** [comment]
Yep, thanks.
