### ISSUE TITLE
Install NextCloud Password Manager

### ISSUE THREAD

**Issue by e-fu** [mail-in-a-box/mailinabox#1645]
//FEATURE REQUEST//

Hi,
how about to install this nextcloud app:
https://apps.nextcloud.com/apps/passman

**Passman**
Open Source Password Manager.

Passman allows you to host your passwords and credentials on your own Nextcloud or ownCloud instance. Independently and open source.

The encryption is done on the client and server side with AES256 bit encryption, to ensure the safety of your credentials.

https://apps.nextcloud.com/apps/passman

Thank you for considering.

**Comment by jacebenson** [comment]
I don't want this on my MIAB.

**Comment by jvolkenant** [comment]
@e-fu Adding new features will be difficult as it adds to the complexity of maintaining this project.  See https://github.com/mail-in-a-box/mailinabox/pull/1588 for a bit of reference

**Comment by JoshData** [comment]
Yeah... On top of what folks said, we've had continual problems with Nextcloud over the years and I don't want to invest any more time on Nextcloud things. I really want to be going away from Nextcloud, but unfortunately I haven't found a good alternative to managing contacts.

So, consequently, I'm going to close this issue. But thanks for the idea.

**Comment by ctrl-i** [comment]
> I really want to be going away from Nextcloud, but unfortunately I haven't found a good alternative to managing contacts.

Have you looked at [Radicale](https://radicale.org/) recently?  I know there was some mention of this a few years back when discussing alternatives.  I have used Radicale for some time without issue.

**Comment by JoshData** [comment]
I'm concerned it's not very actively maintained, but it is a possibility, for sure.

**Comment by ctrl-i** [comment]
> I'm concerned it's not very actively maintained, but it is a possibility, for sure.

True, the last new release was 5 Nov 2018 (barely a year ago) but if there isn't much left to fix then there would be no point in making new releases either :)

**Comment by jacebenson** [comment]
Looks like Roundcube has plugins to add caldav and CardDAV support. https://www.roundcubeforum.net/index.php?topic=24189.0

If this is an option I can open a new issue

**Comment by anoma** [comment]
I dont want to go OT but if this is becoming a "thing" again I would suggest that we seriously consider "solving" this issue by making NextCloud optional.

I say this because I believe in NextCloud  as a proper long term FOSS project that receives timely security fixes and development. This is why its being picked up and deployed at scale by governments.

IMO most users that need or want contacts in MIAB would be happy with NextCloud  and when it breaks they are active in debugging and fixing. The issue is that the other,  potential majority of users, get frustarted as something is broke they dont need or want.

Just my 2c

**Comment by ctrl-i** [comment]
My 2¢ is that if something is part of MIAB then it should not break frequently.  My problem with NextCloud is that it does this and thus drags MIAB down.  I think part of the problem is NextCloud is not very stable and by that I mean it creates new releases often and is constantly adding new features, often these features add little to the core nature of MIAB.  I would prefer a contacts book/calendar solution that does not release often and focuses on providing a contacts book/calendar but has been around long enough to have had the majority of its bugs worked out (which is why I proposed Radicale).

**Comment by anoma** [comment]
That is a very fair argument.

It is hard though to differentiate between a "solid reliable product that releases rarely as it is feature complete" and "a product that is not developed much anymore and isnt fixing privately disclosed security issues in a timely fashion or actively auditing code base against new techniques".

For clarity I am not saying that this fits Radicale I am merely saying NextCloud is well know to pass all these tests.

Regardless of the solution chosen it should be optional as nothing is more stable or secure that not installing a specific feature. I would personally go this route as whilst I use NextCloud I believe it is best handled as a separate full install and not some hobled bespoke mini deployment.

**Comment by ctrl-i** [comment]
> It is hard though to differentiate between a "solid reliable product that releases rarely as it is feature complete" and "a product that is not developed much anymore and isnt fixing privately disclosed security issues in a timely fashion or actively auditing code base against new techniques".

I agree, that is a judgement call that would need to be made but personally I don't think NextCloud fits that.
 
> For clarity I am not saying that this fits Radicale I am merely saying NextCloud is well know to pass all these tests.

I'm not sure it does either, I have used it without issue for over a year but I am not a heavy user of it.

> Regardless of the solution chosen it should be optional as nothing is more stable or secure that not installing a specific feature. I would personally go this route as whilst I use NextCloud I believe it is best handled as a separate full install and not some hobled bespoke mini deployment.

I agree again.
