### ISSUE TITLE
Python maintenance and missing shebangs

### ISSUE THREAD

**Issue by ctrl-i** [mail-in-a-box/mailinabox#1669]
At the time of writing this, python 2.7 has less than 2 months before it is retired - see [Python 2.7 Countdown](https://pythonclock.org/)

I know that running `/usr/local/lib/mailinabox/env/bin/python --version` on my box returns a version number of 3.6.7 but it didn't stop me wanting to check the various python scripts used in MIAB so I did so.

I noticed that two scripts (I am looking at you management/auth.py and management/daemon.py) are missing shebangs.  Should they have one?

Several others (mostly in the tools and tests folders) have different shebangs to those in the management folder.  Should they all be the same?

I didn't spot any MIAB python scripts that were still using python 2.7 but it might be helpful if someone else double-checked this just in case.  If they could a quick confirmation here would be helpful.

**Comment by JoshData** [comment]
> I noticed that two scripts (I am looking at you management/auth.py and management/daemon.py) are missing shebangs. Should they have one?

They cannot be run directly from the command line, so they don't need it.

> Several others (mostly in the tools and tests folders) have different shebangs to those in the management folder. Should they all be the same?

The ones that have shebangs in the management directory do so because they use Python libraries that we install to a virtualenv. The other scripts run fine without any added libraries, so they don't need it. The test scripts are meant to be run by project developers and don't need to be run on a Mail-in-a-Box at all, so the virtualenv may not even be present.
