### ISSUE TITLE
Best mail client? (was "Roundcube and ownCloud contacts")

### ISSUE THREAD

**Issue by hjjg** [mail-in-a-box/mailinabox#169]
Hi,

did you consider syncing the Roundcube address book with the ownCloud address book? There is a [plugin](https://myroundcube.com/myroundcube-plugins/carddav-plugin) for this. @koptein tried this with ownCloud 6. Maybe he is kind enough to integrate it?

It would be nice to have at least a read-only view on your contacts in Roundcube.

**Comment by rockman73** [comment]
Hello - I have a successdful install of Mailinabox at Digital Ocean. It great and thanks so much for making this package!

If I wanted to add another webmail app, how would I go about adding it without changing Mailinabox configutation? I'd simply install the alternate webmail to a different folder / URL.

Cheers

**Comment by rockman73** [comment]
I would also encourage support of ownCloud Mail when it is ready. RoundCube without CardDAV sync makes it appears "tacked" on just to get an email client. 

Since Rainloop is very mature and stomps Roundcube, i don't understand why it can't be included with the Mailinabox project? You mentioned commercial use. It's not clear to me why this is a blocker. Is Mailinabox commercial software? Rainloop is free for personal use - which is the spirit of Mailinabox, yes?

Thanks

**Comment by sqeezy80** [comment]
Because it is not OpenSource. You are right it’s a good looking project under a bad license. Personally i would love to see Mailpile integrated.

**Comment by JoshData** [comment]
> Rainloop is free for personal use - which is the spirit of Mailinabox, yes?

No, that's not true. Mail-in-a-Box ought to be usable by lawyers, journalists, and other professionals for whom email security and privacy is important. And my own two Mail-in-a-Box instances mostly (by volume of email) deal with my professional work, besides also hosting my personal email. Rainloop is definitely out.

I'm going to close this issue because we're not really making any progress on anything here. If and when ownCloud Mail or Mailpile become production ready, let's start a new issue and evaluate at that point.

For those who want to help in the meanwhile, I would suggest:

* Hacking on my Bootstrap-ified Roundcube theme so that Roundcube can be more usable (see earlier comment).
* Helping out the ownCloud or Mailpile devs.
* Starting a new issue about switching to Horde, if you think that would be better.

**Comment by jancborchardt** [comment]
@JoshData just to update you: We released ownCloud Mail 0.1: https://github.com/owncloud/mail/#owncloud-mail :)

**Comment by almereyda** [comment]
@jancborchardt @JoshData + Rainloop now has an AGPLv3 Community Edition https://github.com/RainLoop/rainloop-webmail/issues/8#issuecomment-100014417

**Comment by JoshData** [comment]
Yeah I actually tried installing Rainloop and couldn't get it to work at all.

**Comment by almereyda** [comment]
Anyone https://github.com/whiteout-io/mail-html5 ?

**Comment by JoshData** [comment]
That actually looks pretty nice.

**Comment by MeltedLux** [comment]
Wouldn't it be better to go with owncloud-mail as we are already using owncloud?

**Comment by JoshData** [comment]
Please see my comments earlier in this thread.
