### ISSUE TITLE
Mailinabox on CentOS

### ISSUE THREAD

**Issue by vscarpenter** [mail-in-a-box/mailinabox#182]
I know Mailinabox is designed for Ubuntu but I was wondering if thre was any interest in making this work on CentOS.  Be happy to participate and help.

**Comment by zoof** [comment]
I've used Ubuntu and Debian for many, many years so all else equal, my preference would be for an apt based system.  But all else is not equal -- Centos is supported for 10 years while at best, an Ubuntu LTS is supported for 5 years.  I want to set up a mail server and leave it alone and that seems to me to be the most compelling reason for going with Centos/Redhat.

**Comment by anoma** [comment]
That is a strong argument.

For the sake of debate a counter to this is that currently all LTS variants manage such extended support periods by sticking on primarily old packages. Arguably this is good since it typically also means stable and secure but conversely in a ecosystem like mail I am not sure we are wanting to commit to potentially decade old technologies in the constant war against abuse and spam.

In my opinion as long as the upgrade path is well tested (which it will be since MIAB is essentially an appliance and we all run the exact same OS install) and the recovery path is robust (which it is assuming you make use of the backup feature) then LTS is less important.

I would make a counter argument that less day to day OS level patching is more important to us than >5year base OS support since over the years that is the real consumer of sysadmin hours.

**Comment by zoof** [comment]
I take your point but my understanding, which may be inaccurate, is that Centos/Redhat use old, but maintained versions that get security/bugfixes for the duration of support.  My own experience with my self-built mail server is that spamassassin and postgrey have been pretty robust over time. I don't have experience with the DNS technologies included in mailinabox but postgrey does most of the heavy lifting that then gets cleaned up by spamassassin with very few misclassifications (which I'm sure would be improved if I trained spamassassin).

While the upgrade path may be well tested, it still takes considerable effort -- creating a new VPS instance, setting it up, syncing data, testing, swapping instances.  If older technologies work well enough, for me at least, the benefit of more infrequent OS upgrades outweighs the benefit of having newer versions of postfix, dovecot, spamassassin, etc.

Using Centos/Redhat would also have benefits for mailinabox development as maintenance can focus on a single environment for 7/8 years before needing to think/worry about upgrading the OS.

**Comment by JoshData** [comment]
I'm well past the point of considering re-implementing the whole project on top of a different distribution. It's far more work than I have time to get involved with. Maybe when 14.04 LTS reaches EOL in 2019 we could reconsider all of the options (since transitioning to something else will be time consuming anyway).

**Comment by zoof** [comment]
Sounds reasonable.  I've installed an instance of MiaB and it works wonderfully so far.  Now I've got to think about migrating user accounts and data from my current self/half-baked server...

**Comment by mjhdcode** [comment]
Getting close to 2019 ladies and gents, might be time to consider CentOS 7?

I'm a big, big, Debian family fanboy, but for something like an email server, I don't think there is much debate anymore what distro has it's name written all over that ;)

I'll pledge some hours if it helps - let me know if this sounds good to anyone, I'll send you my real Github...

**Comment by JoshData** [comment]
Several of us have already started working on getting things working on Ubuntu 18.04, so that ship has sailed....

**Comment by zatricky** [comment]
As Josh said, it's a very late prompt. He and a couple of other very determined folk have already made great progress on pushing the project to work with 18.04.

Ubuntu 18.04+ and CentOS are both systemd-based - so very soon having MiaB work on CentOS in a parallel project would not be as hard as it used to be.

**Comment by mjhdcode** [comment]
Drat - just came across the project and I thought it was cool - always worth a shot. Yeah, the systemd tie-in will definitely help, anyway - if/when you get to a CentOS release, I'd be happy to lend a hand with dancing around Selinux, it can be a real pain in the ass...

Anyway - cheers guys - great project

**Comment by zoof** [comment]
As far as I'm concerned, [this](https://www.zdnet.com/article/mark-shuttleworth-reveals-ubuntu-18-04-will-get-a-10-year-support-lifespan/) addresses my concerns re: Centos vs Ubuntu.

**Comment by mjhdcode** [comment]
Yeah - all good, I just never liked Ubuntu or Canonical much - Debian was my go to in my teens but honestly I haven't used much outside of the RPM family lately. Anywho, I opted for installing ISPconfig and just kind of managing the extra software needed by hand. It's no turnkey solution but it hasn't added too much weekly overhead - I'll keep my eyes peeled for a containerized version ;-)
