### ISSUE TITLE
Limit lifetime of user api keys

### ISSUE THREAD

**Issue by fspoettel** [mail-in-a-box/mailinabox#1821]
User API keys issued by `/admin/me` do not have an expiry date set. Tokens are valid until the user password changes. Once #1814 lands, tokens will also invalidate once two-factor authentication is enabled or disabled.

This means that all auth mechanisms are bypassed once an attacker gains knowledge of a key (by MITM, rogue browser extension...) as noted by @downtownallday [here](https://github.com/mail-in-a-box/mailinabox/pull/1814#issuecomment-691596159). Knowledge of a key also provides full access to the admin panel, including password changes and 2FA management.

Ideally, we could limit the lifetime of these credentials. This could be done by encoding it in the token (e.g. use JWT tokens) or use a session-cookie-based approach in the admin panel. Sessions would mean that we would also have to implement API keys for API interactions as proposed already in https://github.com/mail-in-a-box/mailinabox/issues/1217.

**Comment by JoshData** [comment]
This isn't very different from how cookie-based logins work. If you can intercept the cookie, you can impersonate the user. But, as you are pointing out, the lifetime of the token varies. In a cookie-based login, the cookie expires when the user explicitly logs out, some websites will also limit the lifetime of the session (e.g. a few days or weeks), and some websites will also expire sessions when the user changes their password.

For us, the user api key expires when the user changes their password _or_ the master API key changes, which happens when the backend process restarts (so at least on every reboot, although that is hopefully not often).

To force all sessions to expire, the backend process can be restarted (e.g. via a reboot).

Adding the date the token was issued into the token would probably be the easiest change. Allowing the user to expire a token by logging out would require creating a new database table to track sessions.

**Comment by fspoettel** [comment]
> or the master API key changes, which happens when the backend process restarts (so at least on every reboot, although that is hopefully not often).

wasn't aware of that, thanks for pointing it out.

> This isn't very different from how cookie-based logins work.

True, although `localStorage` is less secure depending on how cookies are setup. (Secure flag, HttpOnly flag)

> Adding the date the token was issued into the token would probably be the easiest change.

Sounds like it, although I'm not 100% sure how we could accomplish it. From my understanding, anything in `localStorage` can be tampered with so we would have to symmetrically encrypt the date in some way to prevent tampering. :thinking: At that point we are getting very close to what JWTs try to accomplish. Maybe those are an option for token format?

**Comment by downtownallday** [comment]
Great information. I was mostly concerned about the ability to bypass the second factor (prove you "have something" without revealing what it is). Knowledge of the user api key does that. Obviously, you can't keep asking for it, so limiting the key lifetime seems like a good idea.

**Comment by downtownallday** [comment]
What if you just take the user api key and tack on an expiry date, then encrypt the whole thing with aes-256 using the master api key as the passphrase. Return that as an "extended" user api key.

Verification on the server would involve decrypting, comparing the user key as is done now, but then also ensuring the expiry time has not elapsed.

That would enable key expiry without any backend storage needs.

Expiry should probably be some duration that's about what a normal session takes. An hour?

This scheme doesn't handle expiry at logout.

You could continue to have unexpiring, regular ("non-extended") user api keys when TOTP is disabled. After all, the MITM would have your password anyway.

Maybe that is what was meant by "Adding the date the token was issued into the token would probably be the easiest change?"

**Comment by downtownallday** [comment]
Disabling TOTP should probably require supplying a new TOTP token as well.

**Comment by fspoettel** [comment]
> Disabling TOTP should probably require supplying a new TOTP token as well.

Wouldn't it make more sense to require current password instead (#1822) as is commonly done in these cases? What is the benefit of requiring a TOTP over that? A disadvantage of requiring a TOTP code is that there needs to be a token cycle (30s) between logging in and disabling TOTP.

> then encrypt the whole thing with aes-256 using the master api key as the passphrase.

Yeah that would work.

I'm just not sure whether we should roll our own here or use [encrypted JWT tokens](https://tools.ietf.org/html/rfc7516) since those would also allow us to define custom data such as claims (e.g. _"this token grants rights to alter DNS resources"_) later on and have [decent libraries](https://github.com/latchset/jwcrypto/) available in Python (and other languages that could interact with the API and authenticate via a `Bearer` token).

**Comment by fspoettel** [comment]
btw I would be interested in implementing this once we identified a good way forward and #1814 is merged. Happy with either option pointed out above.
I think the only requirement is that we encrypt things and assume anything we put into localStorage can and will be tampered with as pointed out in the [owasp html5 cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage).

**Comment by downtownallday** [comment]
Short answer: a hacker could steal or guess a password, but they can't reproduce something only you have (the TOTP secret)

Example: the user key (and password) are obtainable by a MITM (eg. your employer implements a MITM proxy and IT can see what you're doing - this was enabled when IT inserted the corporate CA certificate into your Trusted Root Certificate store via Group Policy). As is, the MITM (your IT department) would have the ability to disable TOTP. By requiring a new TOTP token to disable TOTP, it would block that ability (because nobody but you has the TOTP secret - it was never revealed in the user/MiaB dialogue).

**Comment by fspoettel** [comment]
Sorry, I should not have asked a followup question about token input here. :see_no_evil:  Let's please move the discussion of this aspect to #1822 to keep this issue focused on token lifetimes.
