### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by infidelus** [mail-in-a-box/mailinabox#1837]
OK, not so much of an 'issue', more of a help request.

Apart from my MIAB server, I run a couple of other servers on my internal network.  The problem obviously is that they can't all run on ports 80 & 443 so I have to use alternate ports, which makes renewing Lets Encrypt certificates a manual task on the other servers.

I only very recently found out about reverse proxies and am looking for advice/guidance on how to set one up, especially considering the MIAB server grabs all the SSL certificates for the box.

**Comment by kingwarrick** [comment]
I am also trying to accomplish this. Running miab and a ticket support system in containers on the same external ip; would like miab to manage the ssl certificates and also proxy to the container.

The proxying feature is apparently available
https://discourse.mailinabox.email/t/nginx-reverse-proxy/5769/2

and the relevant code
https://github.com/mail-in-a-box/mailinabox/blob/a70ba94b0c2fb77f3f7c23f91eee5d4f3c1620f7/management/web_update.py#L56

But I do not know/cannot find documentaiton how to structure the YAML file, or invoke reading of it.

**Comment by kingwarrick** [comment]
https://github.com/mail-in-a-box/mailinabox/issues/608#issuecomment-279204357

a lesson to me, search and ye might find... @infidelus hopefully this helps you as well.

**Comment by infidelus** [comment]
Thanks, I think I saw that page the other day, but I also misread the relevant post.

I can't test it's working unfortunately as, when I try to visit the proxied page, it gets blocked with:

```
Your connection is not private
Attackers might be trying to steal your information from sub.domain.co.uk (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

and I can't work out how to generate a Lets Encrypt certificate for the proxied site in MIAB.  I've already got the subdomain listed as an A record, but I'm obviously missing something else.

**Comment by kingwarrick** [comment]
If you choose to proxy with the same FQDN but different ports or with aliases, I think the idea is to have MiaB use the nginx proxy after going into ssl, so you shouldn't need certificates on the internal site. That is the route I have chosen, but I am still having issues.

I've got it partially loading my internal site using box.beroldb.ca/ost , but the nginx log now shows that it's trying to access the URI on miab rather than the abc server 

custom.yaml
`
 box.beroldb.ca:
  proxies:
    /ost: https://internal.ip
`

nginx/error.log
`
 [error] 28372#28372: *3124 open() "/home/user-data/www/default/images/oscar-favicon-16x16.png" failed (2: No such file or directory), client: ...., server: box.beroldb.ca, request: "GET /images/oscar-favicon-16x16.png HTTP/2.0", host: "box.beroldb.ca"
`

I think passing the http host is [significant](https://stackoverflow.com/questions/5834025/how-to-preserve-request-url-with-nginx-proxy-pass), but don't know how to set the yaml to pass the http host:

[webupdate.py](https://github.com/mail-in-a-box/mailinabox/blob/7d6c7b66106573881911a9b391f2594846701085/management/web_update.py#L162-L168)
```
pass_http_host_header = False  
m = re.search("#(.*)$", url)  
if m:  
	for flag in m.group(1).split(","):  
		if flag == "pass-http-host":  
			pass_http_host_header = True  
	url = re.sub("#(.*)$", "", url)
```

An admin page would be great, but even putting some explanation in the advanced tips/configuration on the website would be helpful. If someone can shepherd me through to solving this, I can compile something for the page.

**Comment by infidelus** [comment]
I'm obviously doing something wrong.  If I run my internal sites on alternate ports, bypassing MIAB, they get their Lets Encrypt certificates with DNS challenge and work as expected.  If I try to use custom.yaml using something similar to what you've just written, then it fails with the security error.

**Comment by kingwarrick** [comment]
To be sure I understand, are you trying to access the internal sites through subdirectories? e.g. https://blah.com/site1
Or are you trying to use a separate subdomain?

Are you running MiaB and/or the other sites in containers? or baremetal?

I am piggy-backing ost on the MiaB subdomain and certificates. That way, ost does not need its own certificates.

Because of the way MiaB uses symbolic links, and because I am using containers, I had to mount the ssl folder in the ost container to /home/user-data/ssl , and point the apache2 virtual host file for ost to the certificates 

```
/etc/apache2/sites-enabled/osticket-ssl.conf                                                                                  
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin me@me.me
                DocumentRoot /var/www/html
                Alias /ost /var/www/html/ost
                SSLEngine on
                SSLCertificateFile      /home/user-data/ssl/ssl_certificate.pem
                SSLCertificateKeyFile /home/user-data/ssl/ssl_private_key.pem
```

**Comment by infidelus** [comment]
I have a number of servers inside my network.  Some of them have been set up with lets encrypt and just run on different external ports pointing to standard ports (80, 443 etc) on the internal IPs (192.168.x.x) as well as MiaB obviously which runs on standard ports as that's the main server.

None of them run in containers, they're all either physical machines or virtual PCs.

**Comment by melato** [comment]
I set up a MIAB server behind a reverse-proxy (haproxy), and it seems to run fine.  The end user always connects to the standard ports (80/443).  This all happens with LXD containers as follows:
- haproxy container
- MIAB container
- Other web server containers

The LXD host has a firewall that is configured to forward ports 80 and 443 to the haproxy container.  It also forwards the mail ports directly to the MIAB container.

haproxy is configured to send HTTPS traffic to various other servers, including the MIAB server.  For the MIAB domain, it forwards everything to it, except for any subdomains that I want to forward to another web container.

This causes a couple of glitches, which I've worked around:

1.  MIAB detects that it has different public and private IPs, and it shows several status check errors about its services not being publicly accessible.  But they are accessible and they work.

2.  Because of the above errors, MIAB doesn't show the certificate generation button.
As a workaround, I ran management/ssl_certificates.py from the command line.  I had to fiddle with the contents of /home/user-data/ssl a bit, to make ssl_certificates.py generate the missing certificates.  I removed the self-signed certificate and or the ssl_certificate.pem link and then restored the link to the new certificate.  There are two certificates needed: one for the base domain and its immediate subdomains, and one for subdomains box subdomain (for example example.com, box.example.com).  

For the reverse-proxy, I issue a separate wildcard certificate, separate from the MIAB certificate.  I don't use MIAB's DNS.  I've configured the necessary DNS records to my external DNS.  But I think that even if you use MIAB DNS, you can issue a separate wildcard certificate manually from Let's Encrypt, by configuring the required DNS TXT records in the MIAB control panel, as per certbot's instructions.

Haproxy can connect to the MIAB https backend with MIAB's self-signed certificate just fine, without the user getting any warning.  But I wanted to make sure that MIAB has valid public certificates for the mail connections.

I am a new MIAB user.  I don't have much experience with it, but I want to run it in an LXD container, as I do with everything else.

**Comment by infidelus** [comment]
After giving up on this for the last year or so, I went back to it today on a whim, and within about 10 minutes I actually got it working!  No idea why it didn't before, though I have switched from a plain Ubuntu server to Unraid now.

For anyone interested, all I've got in the custom.yaml is:

my.subdomain:
  proxies:
    /: http://my.proxied.server.internal.ip
