### ISSUE TITLE
port 465 SSL/TLS now being pushed as preferred - IANA adds port designation submissions (submission on secure channel)

### ISSUE THREAD

**Issue by ravenstar68** [mail-in-a-box/mailinabox#1849]
RFC 8314 https://tools.ietf.org/html/rfc8314 has been pushing a new standards track deprecating the use of StartTLS completely and recommending all email connections take place over implicit SSL/TLS

The RFC recommends transitioning away from port 587 (although leaving it open during the transition period) and migrating to port 465.

Currently I've done the following:

renamed urd to submissions in /etc/services

`submissions     465/tcp         ssmtp smtps  # URL Rendesvous Directory for SSM`

Amended master.cf to add the following service (based on the existing submission config)

```
submissions    inet  n       -       -       -       -       smtpd
  -o syslog_name=postfix/submissions
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_milters=inet:127.0.0.1:8891
  -o cleanup_service_name=authclean

Opened up port 465 in ufw

**Comment by JoshData** [comment]
Let's do it.

1. I don't think we need to modify /etc/services. The alias `smtps` already in the file will probably work fine in master.cf.
2. Let's use the same syslog_name as the existing submission service to avoid confusion. I don't think we need to support being able to identify the port used. Otherwise management/mail_log.py would need to be updated.
3. fail2ban needs to be updated to close this port.
4. zpush can be updated so that when we eventually turn off port 587 we don't need to change anything.
5. The mail setup instructions in the control panel need to be updated.
6. The iOS and Thunderbird autoconfiguration files need to be updated.
7. Status checks need to be updated to check this port.
8. Some comments in the setup script that mention port 587 need to be updated to mention 465, and security.md needs to be updated.

**Comment by rikoz** [comment]
@JoshData any updates on this feature coming live yet?

**Comment by JoshData** [comment]
This is now implemented.
