### ISSUE TITLE
Nextcloud Contacts search yields 404

### ISSUE THREAD

**Issue by lorrin** [mail-in-a-box/mailinabox#1887]
In Nextcloud contacts, search is no longer working properly for me. If I navigate to a contact (using the list on the left hand side), I get a URL like:
`https://$DOMAIN/cloud/index.php/apps/contacts/All%20contacts/$GUID~contacts`. If I search for a contact (magnifying glass in the top right) and then click on a search result, I get a 404 page and a URL like: `https://$DOMAIN/cloud/apps/contacts/All%20contacts/$GUID~contacts` . Note that the `index.php/` is missing. If I manually put the `index.php/` back into the URL I can view the contact I was searching for.

I believe this is a regression after upgrading to MiaB v0.51.

**Comment by jvolkenant** [comment]
Looks like its fixed with Contacts 3.4.3 specifically with https://github.com/nextcloud/contacts/pull/1972.  The way the code works is we can only update addons versions when you update nextcloud so we'll need to bump up a few things to fix this.

**Comment by jvolkenant** [comment]
I just installed Contacts 3.4.3 and searching and clicking on a name works

**Comment by vikingmedia** [comment]
I've experienced the same problem. Turns out that the contacts expects pretty urls to be enabled, which doesn't seem to be the case in MIAB 0.51 and 0.52 (see https://github.com/nextcloud/contacts/issues/1852#issuecomment-709390862) I have changed the URL generation part in `/usr/local/lib/owncloud/apps/contacts/lib/Controller/ContactsController.php` line 59 from 

```
$url = $this->urlGenerator->getAbsoluteURL('/apps/contacts/' . $this->l10n->t('All contacts') . '/' . $contact);
```
to 
```
$url = $this->urlGenerator->getAbsoluteURL('/index.php/apps/contacts/' . $this->l10n->t('All contacts') . '/' . $contact);
```

then I've reloaded nginx `sudo service nginx reload` and now clicking the search result works

**Comment by jvolkenant** [comment]
https://github.com/mail-in-a-box/mailinabox/blob/af62e7a99bbe2852632daf274a4d8ad29a0cd523/setup/nextcloud.sh#L102

This issue is not fixed yet; in order to update any addons the nextcloud version number needs to be upgraded as well.
