### ISSUE TITLE
_mta-sts record not included into zonefile export.

### ISSUE THREAD

**Issue by ni4** [mail-in-a-box/mailinabox#1925]
While it is correctly displayed on the 'External DNS' page, it is not included into the zonefile text.

**Comment by davDevOps** [comment]
I am not able to replicate the issue.  Any custom configuration you might have?

![image](https://user-images.githubusercontent.com/49919035/108895313-46ffa480-75c8-11eb-830f-a99c07b4668b.png)

**Comment by ni4** [comment]
Hm, now I see it as well. Maybe mislooked something or deleted during removal of main records (as main domain and www point to another location with site's webserver). Sorry for wasting your time for recheck, and thanks for the mailinabox!

**Comment by JoelHough** [comment]
I also just had this issue. It was with a secondary domain with dns handled by cloudflare (imported from miab zonefile), so I had an mta-sts error on my status page until I added the record manually to cloudflare.

**Comment by melato** [comment]
I see this problem most of the time with my domains.  It seems that the problem happens with external DNS, if the domain A record does not point to the MIAB system.  The comments in management/dns_update.py and in #1388 indicate that mta-sts is enabled if, there are valid TLS certificates and that the A record is required in order to get the certificates.  But the certificate can be provisioned just fine if the /.well-known/acme-challenge url is redirected to the MIAB server, through a reverse proxy, even if the A record itself does not point to the MIAB system (but points to the reverse proxy).  I have most of my websites behind reverse proxies, and this is how I got MIAB to issue certificates without the A records it wants.

Once I got the certificates issued, the zone was not automatically rebuilt.  I had to run management/dns_update.py to get the _mta-sts record in /etc/nsd/zones/<domain>.txt, and to get rid of the sticky "MTA-STS policy is missing: STSFetchResult.FETCH_ERROR". 

Since this issue is closed, I may have to enter a new issue.

**Comment by myfirstnameispaul** [comment]
I have lots of domains with external DNS and none have this issue.

Have you configured all of the subdomains handled by MiaB as per the External DNS page? (autodiscover, autoconfig, dmarc, dkim, mta-sts, caldavs, carddavs, etc.). Once those are pointing at MiaB, I can provision certs for the A/AAAA record domains, and some time after that the External DNS page will add the _mta-sts TXT record, and after that the error goes away.

**Comment by melato** [comment]
I've configured all DNS MiaB records, except for the A/AAAA records of the domain itself, since I want to host the domain website elsewhere.  This causes several mailinabox errors.
