### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by Cattoistaken** [mail-in-a-box/mailinabox#1990]
How can i install this https://github.com/badsyntax/mailinabox-ui

**Comment by rfrush** [comment]
Dauxy-  The instructions for running that are in the README.md in the project page, and appear to be pretty clear.   This isn't something you'd run on your MIAB host, but on some other host.  From the demo, it does look pretty slick, but really cannot offer any additional functionality from the stock MIAB webUI.
Also, questions like this are more appropriate on https://discourse.mailinabox.email instead of the github project.  You might get a better response there.

**Comment by DauxyDev** [comment]
yes but i don't care if it doesn't add any functionality (sorry if that sounds rude). and the instructions are for locally
