### ISSUE TITLE
Has someone tested this on Debian?

### ISSUE THREAD

**Issue by sitemapxml** [mail-in-a-box/mailinabox#2030]
I have read in your installation guide that, if we deploy to digitalocean the droplet should be Ubuntu 18.04. I have used ubuntu server for a while, and I am unhappy with too much frequent updates, which have broken my system two times. Now I want to move to debian as it is more stable compared to ubuntu. 

If this is made for ubuntu, it should work on debian too, but I would like to know if someone have tested it before me. 

Any kind of information is appreciated.

**Comment by nomandera** [comment]
Think of mailanbox more as an appliance than a package and you will understand why the very best case answer to this would be `almost certainly doesnt work and even if it did it would be unsupported`.

The OS component choice is very specific and unwavering and changing even to newer versions of Ubuntu requires careful planning and rigorous testing.

**Comment by sitemapxml** [comment]
Thank you for your answer. I think I understand you. 
There are, however, a question bothering me... Why would developer of this project decide to use Ubuntu server over Debian?
If you are going to have your own mail server you don't need updates every two or three days... Last year my websites were down two times because of breaking updates in Ubuntu. That is why I have migrated all of my web apps to Debian.

**Comment by Synchro** [comment]
I'd say the most important thing is that Ubuntu has a solid, predicable release schedule and Debian doesn't. The vast majority of updates in Ubuntu are exactly the same as Debian, because to large extent ubuntu *is* Debian. In both (by the same mechanism no less), you can choose what sets of packages you want updated, so you could for example configure your server to only ever install updates from the security branch (the bare minimum). If you run a mail server (a permanently connected internet device with a lot of installed packages and a large attack surface), updates every two or three days are *completely normal* in any modern Linux, since that's about how often security issues are patched.

**Comment by JoshData** [comment]
> Why would developer of this project decide to use Ubuntu server over Debian?

It's what I was most familiar with. There isn't really anything deeper than that.

**Comment by sitemapxml** [comment]
Thank you for your answers. 
@Synchro Good point on updates, I missed that.
@JoshData That was case with me too... There were multiple projects that I made specifically for Ubuntu, and later trying to adapt that projects to some other system :smile:

**Comment by ValdikSS** [comment]
You can always install ubuntu+MiaB in a container or a VM. I use LXD, works perfectly.

**Comment by busterbeam** [comment]
I want to test how this thing works on my desktop, I'm not going to reinstall my OS on my daily driver machine...

I really don't get why you didn't focus on Fedora(RedHat), Debian and arch(?), being the roots of almost all OSes.  

> Think of mailanbox more as an appliance than a package

Sure all "packages" come with "programs" e.g. "appliances", doesn't change the fact that you make an install that will work on a minimum Linux install and then work your way out to work on the more niche OSes such as Ubuntu.  This really shouldn't be that complicated.

**Comment by Synchro** [comment]
Ubuntu is the world's most popular Linux distro for servers; it's not in the least bit "niche". As I mentioned above, it's essentially Debian with a more predictable release schedule. An Appliance is typically configured to do _one thing_ well. It's not intended to work on every Linux distro (and just as well; I've been suffering from the blight that is Centos lately). The more rudimentary the distro, the harder it is to configure. While I'd like to see MIAB have more abstraction (e.g. built with Ansible rather than custom scripts) so that it could get away from being quite so nailed to the distro, expecting it to work on distros that lack important packages is not something I'd want nor expect. If you do expect that, MIAB probably isn't for you, or it awaits your PRs.

**Comment by JoshData** [comment]
Closing & locking for what should be obvious reasons. I answered the "why" question pretty clearly last year. Not interested in complaints disguised as questions.
