### ISSUE TITLE
Install Fails - Clean Ubuntu 22.04

### ISSUE THREAD

**Issue by daygle** [mail-in-a-box/mailinabox#2179]
Attempting to run installation on a clean Ubuntu 22.04.01 and receive the below errors when running - curl -s https://mailinabox.email/setup.sh | sudo bash. Any ideas why? Works when I run on Ubuntu 18.

Attempt 1
![image](https://user-images.githubusercontent.com/5925233/196170681-a3c3d45e-f675-43f1-b9e0-756f8033f449.png)

Attempt 2
![image](https://user-images.githubusercontent.com/5925233/196333441-596c787c-5c3b-42d4-9ee0-5e7beac5a3fa.png)

**Comment by stylnchris** [comment]
What VPS company?    Is the box resolving dns properly?        can you ping www.google.com from cli?     

based on the output it looks like it can't download the packages?

**Comment by daygle** [comment]
Using RackNerd (KVM machine).

Yeah the box is resolving correctly - no issues there. Weird? Maybe it's an issue with the OS template provided by RackNerd?

**Comment by daygle** [comment]
Just as I expected an issue with RackNerds template. Had to get them to mount the latest Ubuntu 22.04 ISO - ran again and worked.

Anyway someone else may come across this issue.

**Comment by jwest31337** [comment]
I wanted to give a shout out to @daygle for mentioning the RackNerd problem here. I also have a VPS there and was beating my head against the desk trying to figure out why this wasn't working, and didn't even consider that a custom template may have been used. Thanks so much for figuring this out.

In case anyone else is using RackNerd and wants a lazy workaround: You can install Ubuntu 20 instead of 22, and then do a dist-upgrade to 22 and it will overwrite their template settings, and then you can install MiaB without any errors.

**Comment by daygle** [comment]
Thanks @jwest31337, happy to help.
