### ISSUE TITLE
gmail - IP address sending this message does not have a PTR 

### ISSUE THREAD

**Issue by MishaVernik** [mail-in-a-box/mailinabox#2211]
Hi there community, if someone had a similar issue please let me know, tried a lot of things...
https://dnschecker.org/#A/box.sellsgram.com PTR - OK
 84.46.242.76 | box.sellsgram.com
 
 host gmail-smtp-in.l.google.com[142.250.27.26] said:
    550-5.7.25 [84.46.242.76] The IP address sending this message does not have
    a 550-5.7.25 PTR record setup, or the corresponding forward DNS entry does
    not 550-5.7.25 point to the sending IP. As a policy, Gmail does not accept
    messages 550-5.7.25 from IPs with missing PTR records. Please visit
    550-5.7.25  https://support.google.com/mail/answer/81126#ip-practices for
    more 550 5.7.25 information.
    du14-20020a17090772ce00b00780ec98afafsi1640581ejc.113 - gsmtp (in reply to
    end of DATA command)

**Comment by cdp1337** [comment]
Have you given it a little bit of time for Google to realize it?  Sometimes it may take a few days.  Also just checked that myself and yup, you *do* have it setup correctly for as much as I can tell.

@JoshData this isn't an issue with miab but is still useful for users to follow.  Look at Github's Discussion feature, it may make sense for these types of questions to be asked there since they are not directly related to a feature request / bug.

**Comment by MishaVernik** [comment]
To those who get the same:
1. I waited 1 day - after registration 
2. Added my domain https://postmaster.google.com/u/0/managedomains (got it verified, because before it messages got in the spam section in GMAIL)
3. Sent from multiple .gmail emails to my domain and after reply got into spam and marked it as "Report Not Spam" (did it 3 times)

By now looks good.
