### ISSUE TITLE
Option to disable/configure backups

### ISSUE THREAD

**Issue by pryley** [mail-in-a-box/mailinabox#228]
My server is incrementally backed up daily to Amazon Glacier. For this reason, having a daily mailinabox backup running is not needed and would quickly fill up my 30GB HD server limit (I have 60+ email account across 6 domains).

I see that I can remove the daily mailinabox backup cron job, but manangement.sh implies that it would be reactivated on update.

It would be nice to make backups optional.

**Comment by shibby** [comment]
Hello there,
For a reminding, i got trouble with backups. I have 20 gb hdd on my vps and after system backup, there was ne left any space. Manually deleted backup folder, now it is fine. But there need to be a backup option. For example, i dont want to backup owncloud data.
Sorry for bad English :) 
Thanks.

**Comment by razem-io** [comment]
I also have a problem with the backup option. I mounted the user-data folder to another server via sshfs in order to be able to use owncloud as a file storage. With 100GB+ the backup takes forever. As a result I am not able to recieve/send mails or access owncloud during this time.

Has anybody found a workaround for this issue?

**Comment by Futurama56** [comment]
+1

**Comment by Futurama56** [comment]
Just a switch would be nice in the admin 

on/off

**Comment by JoshData** [comment]
Fixed in 9ca116d54537943ee65bb1e3368df9c802e43dcb.
