### ISSUE TITLE
Requesting to Create Uninstall script 

### ISSUE THREAD

**Issue by sivanaikk** [mail-in-a-box/mailinabox#2292]
The installation is really good. It's hard to uninstall and it's a nightmare if we install it on an existing server.

**Comment by JoshData** [comment]
It would be incredibly difficult to roll back the hundreds of system configuration steps that are performed. It's just not feasible. And starting with a server that has had other changes makes it incredibly difficult to know if the installation will work at all. That's why all of the documentation says to start with a fresh server. It's a part of the foundational architecture of this project that a fresh server identical to what everyone else is using is the only way for this project to be successful.
