### ISSUE TITLE
BUG: API with authorization by API key doesn't work

### ISSUE THREAD

**Issue by il2020** [mail-in-a-box/mailinabox#2448]
Trying to use the key from /var/lib/mailinabox/api.key:
```sh
KEY=$(cat /var/lib/mailinabox/api.key) && curl -X GET -H "Authorization: Basic $KEY" https://example.com/admin/mail/aliases
```

And I'm getting an error:
```text
'ascii' codec can't decode byte 0xb0 in position 1: ordinal not in range(128)
```

I'm using Mail-in-a-Box v69b.

**Comment by downtownallday** [comment]
There is no bug. The Basic authentication scheme requires the username and password be base64 encoded.

See https://www.rfc-editor.org/rfc/rfc7617.html

You can just use curl's -u argument instead of appending the header manually. `curl -u "$KEY:" https://example.com/admin/mail/aliases`, or use the management/cli.py tool.

**Comment by il2020** [comment]
> There is no bug. The Basic authentication scheme requires the username and password be base64 encoded.
> 
> See https://www.rfc-editor.org/rfc/rfc7617.html
> 
> You can just use curl's -u argument instead of appending the header manually. `curl -u "$KEY:" https://example.com/admin/mail/aliases`, or use the management/cli.py tool.

Thank you. I found that solution on the forum: https://discourse.mailinabox.email/t/api-requires-2fa/7222/2
It would be great if there were instructions on how to use the API key in the admin area.
