### ISSUE TITLE
Please consider using a GNU+Linux distribution that is not spyware

### ISSUE THREAD

**Issue by alithechemist** [mail-in-a-box/mailinabox#2455]
As the title says, I wish this project could run on a serious upstream (like Debian) or a better distribution in term of users rights and privacy (as opposite of mass-surveillance). 

Ubuntu is not so great for this and I'm not the only one thinking this way: 

Also Doc. Stallman has something to say about it.
https://invidious.classictetris.net/watch?v=CP8CNp-vksc

Maybe Trisquel can do this? it's very close to Ubuntu, it is made by GNU, which makes it trustworthy.

I can test an instance if you like.

I'm not asking to add support for a new OS, I' m asking to stop using Ubuntu and proposing an alternative.

I'm sure many more people would run MIAB if it ran on Trisquel or Debian
 
Thanks for the attention and for your work.
Have a nice weekend,
Chip

**Comment by myfirstnameispaul** [comment]
> I' m...proposing an alternative.

Where is the PR?

**Comment by alithechemist** [comment]
Well i did not go all the way to the point that i can do a PR, it's a lot of work, so, before that i'd like to know your opinion and how attractive this can be for you.

**Comment by Synchro** [comment]
As you say, this would be a lot of work, but I'm not convinced it's worthwhile. That video is 11 years old, and Ubuntu removed that search feature 8 years ago, though even then the search system described is exactly what Google *still* does (and that's OS-agnostic), and Debian only dropped Google as the default in 2022. If you have more specific complaints, along with reasonable solutions, please list them here.

**Comment by myfirstnameispaul** [comment]
My best guess is that it would exist as a forked project. It is a huge task to migrate a mail server.

**Comment by JoshData** [comment]
> in term of users rights and privacy (as opposite of mass-surveillance)

I don't know of any privacy or surveillance issues that actually affect live Mail-in-a-Box boxes (if I'm wrong please open an issue about it), so I think you're raising a philosophical rather than technical issue.

There's nothing wrong with philosophical issues. That's fine.

But we're constrained by distros that are readily available at hosting providers _and_ that are _easy_ to build on top of. Debian is, in my (somewhat limited) experience, the only other option. If I were starting over today, I would certainly consider it.

But it is just too big of a change. Nobody here has time to do it and support the entire Mail-in-a-Box community in the change.

**Comment by myfirstnameispaul** [comment]
Not sure if this counts, but each new SSH session dynamically sends data when loading the MOTD:

https://ma.ttias.be/what-exactly-being-sent-ubuntu-motd/

(o;

**Comment by JoshData** [comment]
> each new SSH session dynamically sends data when loading the MOTD:

Please open a new issue (but check that that's actually happening on your box first).

**Comment by z3r0-gr4v1tY** [comment]
I wish they would offer a Gentoo build))) xd
