### ISSUE TITLE
Sending mail using Z-Push doesn't set a nice From: name

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#255]
The From: header on outbound mail send via Z-Push is always just the email address. At least as reported here:

https://discourse.mailinabox.email/t/getting-z-push-to-use-an-identity/139

The fix is related to this:

https://github.com/fmbiete/Z-Push-contrib/blob/566c52e053d40c60495b3e5628149565b55b783e/backend/imap/imap.php#L2230

**Comment by fmbiete** [comment]
About the sql injection through the username, that won't be posible. Because if the username is not a valid account in your mail system that code will never run.

**Comment by JoshData** [comment]
@fmbiete Thanks for that info.

I'm OK adding a field to the database for this purpose, adding a simply way in the admin to set it, and the rest needed to make this work. But it's not a priority for me so I probably won't get around to this myself for a while.

**Comment by electrickite** [comment]
Another idea might be to use the Roundcube identities table to set the Z-Push from name rather than the MIAB users database. This has the advantage of allowing users to set their own from name (through Roundcube), and makes it consistent between ActiveSync and webmail.

If that sounds like a reasonable approach, I'd be happy to submit a PR.

**Comment by JoshData** [comment]
Sure, if it's easy.

**Comment by JoshData** [comment]
Fixed by the above PR.
