### ISSUE TITLE
drop z-push 

### ISSUE THREAD

**Issue by nstanke** [mail-in-a-box/mailinabox#256]
Z-Push related issues all over the place.

#205 #187 #235 #255 #126 #253 

I would love to use ActiveSync, unfortunately I don't think z-push is suitable for this project at the moment.

Any thoughts on removing z-push, until major issues are fixed?

**Comment by bl00513** [comment]
I'd like to weigh in on this suggestion... I'm using iOS 8.1, and the only problem I've run into so far (related to z-push) has been with contact syncing. I'd be hesitant to completely drop application, as it does provide a very useful service for iOS users. Unless there is something similar that is less flakey, I suggest that removing z-push may be a tad be drastic.

**Comment by sqeezy80** [comment]
With iOS there is nothing you need Z-push for aside for Pushing e-mails to the
device, wich is also archived in pulling mails every 15 minutes, via manuall
setup. Every other service should be installed pretty automatic if you use the
configuration file for iOS https://yourdomain/mailinabox.mobileconfig and it
should also be more gentle on the battery this way.




On Wed, Jan 07, 2015 at 12:36:56PM -0800, bl00513 wrote:
> I'd like to weigh in on this suggestion... I'm using iOS 8.1, and the only problem I've run into so far (related to z-push) has been with contact syncing. I'd be hesitant to completely drop application, as it does provide a very useful service for iOS users. Unless there is something similar that is less flakey, I suggest that removing z-push may be a tad be drastic.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mail-in-a-box/mailinabox/issues/256#issuecomment-69087627

--

**Comment by bl00513** [comment]
I should have been more specific. I definitely see what you are saying
here. I know iOS users could simply use imap, but with 15 minutes being the
minimum pull interval it might not be the best option. Others feel free to
chime in, but I am accustomed to being notified immediately of new email. I
think that's a huge advantage that z-push delivers. I just don't see where
scraping it would deliver benefits that outweigh instant notification of
email + calendar and contact syncing.

On Wed, Jan 7, 2015 at 4:43 PM, sqeezy80 <notifications@github.com> wrote:

> With iOS there is nothing you need Z-push for aside for Pushing e-mails to
> the
> device, wich is also archived in pulling mails every 15 minutes, via
> manuall
> setup. Every other service should be installed pretty automatic if you use
> the
> configuration file for iOS https://yourdomain/mailinabox.mobileconfig and
> it
> should also be more gentle on the battery this way.
>
>
>
>
> On Wed, Jan 07, 2015 at 12:36:56PM -0800, bl00513 wrote:
> > I'd like to weigh in on this suggestion... I'm using iOS 8.1, and the
> only problem I've run into so far (related to z-push) has been with contact
> syncing. I'd be hesitant to completely drop application, as it does provide
> a very useful service for iOS users. Unless there is something similar that
> is less flakey, I suggest that removing z-push may be a tad be drastic.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/mail-in-a-box/mailinabox/issues/256#issuecomment-69087627
>
> --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mail-in-a-box/mailinabox/issues/256#issuecomment-69097412>
> .
>



-- 
Best Regards,


*Ben Luke*
E: bl00513@gmail.com





 ------------------------------
This message is private and confidential. If you have received it in error,
please notify the sender and remove it from your system.

**Comment by JoshData** [comment]
@bl00513 Thanks for writing about your success with Z-Push. It's hard to make progress on this only hearing from those that had problems.

And, of course, if Z-Push works, then yeah we'd want to keep it. The problem we ran into is that it wasn't working for everyone, and I agreed that this was a problem. This project is about making something that "just works", and Z-Push was standing in the way of that.

If we can make it just work, then I'd be glad to put it back as the recommended method for iOS users. Until then, it can't be recommended. I'm not happy about keeping it in as an alternative (I prefer to do one thing that works and do it well, rather than offering options), but since it works well enough for some and it offers a clear advantage I'm not planning on pulling it entirely.

**Comment by h8h** [comment]
As I already described here #287 Z-Push works even fine for android devices with its build-in app `Corporate` (Microsoft Exchange). Since I discovered this app I think we should keep Z-Push.

Maybe we need some more android testeres and if everything works fine, we could provide one interface for android and iOS devices. No need to give recommendations for davdroid or k9-mail. I love both apps but for inexperienced users it could be a benefit to use the buildins. 
It does not matter which device you use (android or iOS) just type-in your data here or here and there you have your mails, your contacts and your calendar. I would love to say this one day :).

**Comment by nstanke** [comment]
Since Z-Push is working great on our BB10 devices I would prefer to keep it (and apprently Android aswell) but don't recommend it for iOS users.

**Comment by rockman73** [comment]
Z-Push works great with Windows Phone 8.1. However, calendar syncing is a bit wonky. I get a birthday calendar synced (that I can't see in ownCloud) but my main calendar use is not synced. It synced a shared calendar once, but subsequent setups fail to sync it anymore. I'm still trying to root out the issue. This is on ownCloud/Z-Push, not Mailinabox.  i don't see another option option to get contact & calendar sync on Windows Phone 8 without something like Z-Push. I say keep it as it can easily be ignored otherwise.

Could it be a Mailinabox setup option to enable/disable Z-Push?

**Comment by JoshData** [comment]
Guys, guys, as I said above, I'm not planning to remove Z-Push. We don't need to debate that. :)
