### ISSUE TITLE
CentOS 6 port anyone?

### ISSUE THREAD

**Issue by grepwood** [mail-in-a-box/mailinabox#280]
I'm porting miab to CentOS 6 and most of the Ubuntu-specific bits and pieces have been taken care of in my fork. Some of the PHP plugins are missing and they might not be available for a while.
Right now I'm adjusting Python 3 code to work on Python 2. There is an interesting bug with `dialog` that makes all `if [ -z "$EMAIL_ADDR" ];` tests succeed.
Consider these files:
https://github.com/grepwood/mailinabox/blob/master/setup/functions.sh#L156
https://github.com/grepwood/mailinabox/blob/master/setup/questions.sh#L46
Would that still work on Ubuntu?

**Comment by santiagon610** [comment]
> Because I'll need it on CentOS 6 for a while.

@grepwood, I'd be in favor of any kind of CentOS/RHEL port, as I'm stuck using that at my work due to a multitude of reasons. Happy to assist with testing.

> Why Centos 6? There's already 7, and python3 is available on it.

@zkanda, I know some organizations are still standardized on EL6, so I'm not sure if that's @grepwood's rationale, but I know that my organization is still doing that. Not sure if an alternate repo offers python3, but these build instructions are available, of course: http://stackoverflow.com/questions/8087184/installing-python3-on-rhel

**Comment by grepwood** [comment]
@santiagon610 check out https://github.com/grepwood/mailinabox and issue #295
Beware that somewhere along the way support for Ubuntu broke and troubleshooting it is more difficult than CentOS due to no logs or warnings offered by the main nginx binary
