### ISSUE TITLE
AAAA, IPv6 for SPF

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#3]
Add AAAA records: If the system is on an IPv6 network, the DNS should add AAAA records.

And SPF should be tested that it approves the IPv6 address. According to maco_nix, gmail will reject mail if a system has an IPv6 address and SPF doesn't approve it.

(This issue formerly also listed DNSSEC, but I've moved that to #71.)

**Comment by jabbink** [comment]
IMO not resolved as mailinabox suggests a SPF record which only checks the MX records (and in my situation setting the AAAA record for dom.ain to my ipv6 was not usable).

Cleaner would be to just set the MX record to eg. mx.dom.ain (as it's done)

Set the A record for mx.dom.ain. to the ipv4 (as it's done already)

Set the AAAA record for mx.dom.ain to the ipv6

Set `smtp_bind_address6` to the same ipv6 in `/etc/postfix/main.cf`

PS: Almost forgot why I needed this: my server has a /64 block of ipv6's assigned and otherwise takes a random one when connecting to gmail...

**Comment by JoshData** [comment]
Interesting....

**Comment by jabbink** [comment]
(Also to be extra safe, maybe setting `smtp_bind_address` is also useful, as some people may have multiple IPv4's)
