### ISSUE TITLE
Web configs use local.conf not sites-enabled

### ISSUE THREAD

**Issue by mathuin** [mail-in-a-box/mailinabox#335]
nginx allows for site-specific configuration files which seems to be more appropriate than the creation and modification of a local.conf file.

Also, it would be nice to provide hints to those configuration files, so "ssi on; index index.html index.htm index.shtml;" could be automatically added to a particular site's config -- otherwise, my wife's portfolio will stop working every time mailinabox updates. :-)

**Comment by JoshData** [comment]
Hello,

> nginx allows for site-specific configuration files which seems to be more appropriate than the creation and modification of a local.conf file.

It's just a file path. I don't see a substantive reason to change it. Especially since it is not intended to be modified by the user.

>  it would be nice to provide hints to those configuration files

Since Mail-in-a-Box's focus is on mail and not web, I don't intend to allow much custom configuration for nginx. It's just too complex to make a reliable system that is everything to everyone. To do something more advanced than static files, you should set up a separate server (and set a custom DNS A record).

There is a hidden feature to inject statements into the nginx configuration file, but you'll have to find it.
