### ISSUE TITLE
Web Hosting as docker nginx services

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#337]
I see over and over again people requesting changes to www hosting options that are out of scope for mail in a box. These kind of requests will never go away.

I also see some discussion on migrating mail in a box to become a docker container (hard as MIAB is so complex).

However coming at this from the other direction, would it be worth thinking about splitting MIAB nginx into two separate daemons:

The default nginx install moved to an oddball port dedicated to MIAB config
A second dockererzed nginx instance for all public web hosting.

By mapping the config files into a volume it should be possible to allow users full control of nginx along with PHP et al with no risk of breaking the MIAB config interface or attacks escalating out of the container.

The only risk is that once the pandora's box of docker is opened users may put too much pressure on their small servers however conversely it does allow users to make absolute best use of their servers.

**Comment by JoshData** [comment]
I can see why users would want to save money by putting more services on the box instead of spinning up more hardware, but the goal of this project isn't to save people money. Whatever one had to do to get a PHP website running before, it's the same with Mail-in-a-Box. The box doesn't make it harder or any more expensive. It just doesn't make it less expensive.

I get that there are technical ways to combine things, but I just don't want to be the one supporting PHP. It falls on me to make sure the box stays up to date with security patches, that instructions are clear, and that questions on the forum get answered. I just don't have time to do that for a more complex project. That means it can't be an option within the project. (I wouldn't object to a fork that had its own community forum etc.)

The best route is to make Mail-in-a-Box be friendly with side-by-side solutions (currently a separate server, if Mail-in-a-Box can be dockerized than a parallel docker container).

**Comment by anoma** [comment]
I understand what you are saying and to some extent I totally agree. However by trying to add extra justification to my OP I may have lessened my own case. 

I still think there is merit in splitting nginx in this way even if you stick to the current static-only capabilities of public hosting. By doing so you gain the advantage of containerization, security and  dependency hell.

There is a lot to be said for keeping public completely locked way in a jail and the config daemon completely separate. There is precedent for this e.g Plesk etc albeit no one has fully realised the power of docker as far as I know.

Something to consider is that by allowing docker you could in theory reduce your overhead as your support burden would stop at the docker level. In this way MIAB becomes a mail only server (no ww at all) but with the framework to add it.

Ponder it and if it still is not viable give some thought to just allowing docker to be installed without breaking the clean install Ubuntu requirements.

**Comment by JoshData** [comment]
Sorry I still don't really see the point. If the project is going to provide at most static web hosting, I don't see the reason (security or otherwise) to have two nginx's. Whatever minimal security advantage there is, it is entirely out-weighed by having more complexity.

I'm going to close the issue but feel free to keep discussing.

**Comment by anoma** [comment]
I am happy with that. What I would like though is to be able to install docker as a means to leverage more capabilities out of the hardware.

My concern is that if someone does install docker then MIAB will potentially get confused by the extra bridge ethernet interfaces 

e.g.

docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:606 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:46988 (45.8 KiB)  TX bytes:1140 (1.1 KiB)

As far as I can tell apart from this installing docker should have no impact on MIAB at all.
