### ISSUE TITLE
On-Disk Encryption

### ISSUE THREAD

**Issue by martindale** [mail-in-a-box/mailinabox#345]
In case the server is physically compromised or the drive is otherwise imaged (in the case of VM host backups, for example), the entire disk should be encrypted so that it cannot be read.

This may be as simple as using an encrypted loopback file.

**Comment by dhpiggott** [comment]
Can you describe how you think key management should be handled? The problem I've always had in the past when I've used FDE on servers is with that. I always used LUKS with a passphrase, which meant that I had to be manually mount the encrypted data partitions post-boot. As such the machines were not capable of resuming normal operation when rebooted due to e.g. Xen security updates causing the hosts to schedule unavoidable reboots. It was that problem which eventually made me give up on FDE, and I think for the same reason enabling it in MIAB might be too user unfriendly.

**Comment by JoshData** [comment]
This is a dup of #27.
