### ISSUE TITLE
Not be a mail server that the NSA cannot hack.

### ISSUE THREAD

**Issue by starkers** [mail-in-a-box/mailinabox#351]
Sorry for being a nerd but I saw this: in the readme:

- **Not** be a mail server that the NSA cannot hack.

I'm sure its just a grammatical error but I assume don't want the NSA to be able to compromise this?
Could I suggest changing it to:

- **Not** be a mail server that the NSA can easily hack.

Sorry for being a lingual geek but I speak languages where double negatives are used to mean positives and my father is an English teacher so this jumped out at me.

Look forward to trying this out -david

**Comment by dhpiggott** [comment]
I too saw this when I first encountered and evaluated mailinabox, but I didn't see it as an error. I interpreted it as meaning:
* Mailinabox makes no claim of being unhackable by the NSA, but it is developed with security in mind, and it does *aim* not to have any vulnerabilities.
* If it does *happen* to be unhackable by the NSA (or any well resourced and determined attacker for that matter), that is a bonus - but such threats are not a primary design consideration.

**Comment by JoshData** [comment]
That's right. The project will address some threat models but not others. There is no end to the hypothetical attacks one can imagine the NSA might do. We're not going to address them all because they come at the cost of other project goals. So, for instance, a physical compromise of the machine is a threat model that I have deliberately decided is out of scope (e.g. see #27).

**Comment by starkers** [comment]
Aye, its not like email was ever designed for security.. that'd be more the remit of DIME etc.

Thanks for the clarification :)
