### ISSUE TITLE
password hashes world readable and read/write by www-data group

### ISSUE THREAD

**Issue by chuckpeters** [mail-in-a-box/mailinabox#369]
root@box:~# ls -l /home/user-data/mail/users.sqlite 
-rw-rw-r-- 1 root www-data 6144 Mar 28 16:06 /home/user-data/mail/users.sqlite

This seems like it is a security issue, especially if we want to offer shell access.

**Comment by JoshData** [comment]
The security model I've been working under is that the only people with shell access are admins.

The permissions are intentional (see setup/webmail.sh), though it's possible we could make it more restrictive. We'd need to test that postfix, dovecot, the Roundcube password changing plugin, and the management daemon still have access. Maybe other things I'm forgetting.
