### ISSUE TITLE
Roundcube download not validated with https or checksum

### ISSUE THREAD

**Issue by chuckpeters** [mail-in-a-box/mailinabox#370]
https://roundcube.net/download/ doesn't respond at all.
https://www.roundcube.net/download/ shows an invalid certificate, github.
SourceForge doesn't seem to have any checksums or GPG sigs.

The installation of Roundcube could be tampered with and I'm not seeing an easy solution to this one because Roundcube isn't offering https, gpg signature file or something I might trust. md5sum is not sufficient against a well funded attacker, especially when it is all http in the clear.

I filed a bug report upstream:
http://trac.roundcube.net/ticket/1490345

It looks like /root/mailinabox/setup/webmail.sh deletes the source after the install making it almost impossible to verify the md5 checksum after the install.  For now, could we offer an option to email the admin the checksums (md5 and sha256) and include a link to http://roundcube.net/download/?

If you don't want send email with an update to Mail-in-a-Box, how about logging the checksums some place or display it during the upgrade?

Using one of the above suggestions, I could at least download Roundcube at various locations and check the checksum.  In the future, I hope we can use a strong set GPG key or something during the upgrade.  I need to look at this more detail to determine if I would trust it, put the sha256 checksum in a DNSSEC validated zone and check it against roundcubesha256sum.example.org.

**Comment by JoshData** [comment]
We will put a checksum right into the Mail-in-a-Box sources one day (like [here](https://github.com/mail-in-a-box/mailinabox/commit/dd6a8d99981e04a21d4855da3568ad93c3cf9682#diff-73f608f26010883824d6e09c61781cb9R24)). Since we're dealing with fixed versions of things, there's no need to make that part too complicated.

I sign all of the Mail-in-a-Box git tags, btw, and that's how we can get to trusting checksums stored in the repository. Just need some documentation explaining, and the [bootstrap script](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/bootstrap.sh) needs to be modified check the tags (on installation download key from mailinabox.email; on upgrade validate against locally stored key).

Feel free to submit a PR that does a SHA256 checksum of the downloaded file [here](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/webmail.sh#L50).

**Comment by JoshData** [comment]
Fixed in 2a1704a0dcce0648f10bcb3701fe1b961ba7f329.
