### ISSUE TITLE
Port forwards

### ISSUE THREAD

**Issue by jkaberg** [mail-in-a-box/mailinabox#373]
I'm just about to set up mail-in-a-box on my Rpi2 (as there's an Ubuntu 14.04 image out in the wild)

Looking over the docker image I see the following ports 

TCP:
80 443, 587, 993
TCP/UDP:
53

Am I missing anyone? I will be running the Rpi from home :-)

**Comment by dhpiggott** [comment]
You can't go wrong if you match the UFW rules that MIAB sets up:
```
david@elm:~⟫ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
25/tcp                     ALLOW       Anywhere
587                        ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
53                         ALLOW       Anywhere
993                        ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
25/tcp (v6)                ALLOW       Anywhere (v6)
587 (v6)                   ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
53 (v6)                    ALLOW       Anywhere (v6)
993 (v6)                   ALLOW       Anywhere (v6)
```
I presume you're deliberately not exposing SSH outside of your LAN, so I think the only discrepancies to note are that SMTP (on 25) needs to be TCP, not UDP, and that DNS (on 53) can actually be TCP or UDP (I believe UDP is more common but that TCP queries can/do occur).

I think the existence of UDP rules for other ports is not because they are required but because `/etc/services` doesn't specify TCP only for them - so I also wouldn't create UDP forwarding rules for 80, 443, 587 or 993.

I'd be interested to read more about how you get on with running on the Rpi :)

**Comment by jkaberg** [comment]
Thanks @dhpiggott, I'll keep you posted but it should be a straight forward setup

https://wiki.ubuntu.com/ARM/RaspberryPi

:-)
