### ISSUE TITLE
Unable to replace multi/wildcard certificate

### ISSUE THREAD

**Issue by nstanke** [mail-in-a-box/mailinabox#391]
At the moment I use a SSL certificate which is valid for `box.mydomain.com` and `mydomain.com`, hence the SSL page shows that `mydomain.com` use the "multi/wildcard certificate of `box.mydomain.com`. Unfortunately it's not possible to replace the SSL certificate of `mydomain.com` although no error is given.

I'm on 1f08997a9e5afe08ec3eedd2897f8073e4fa0bc2

-Norman

**Comment by JoshData** [comment]
Seems like once the main cert works for a different domain, it will always prefer that one. The idea is to supersede the automatically created self-signed cert as soon as a better one is found. [This line](https://github.com/mail-in-a-box/mailinabox/blob/master/management/web_update.py#L160) would need to be revised to only prefer the main cert if the domain-specific cert is self signed, otherwise prefer the domain-specific cert.

**Comment by JoshData** [comment]
Fixed-ish by #268 - there's no longer a reason to worry about installing certificates.
