### ISSUE TITLE
v0.11 release candidate - please test

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#458]
Hello! I'm planning on releasing the current `master` branch as version v0.11. If you can, please try out this branch and let me know your experience. Thanks!

**Comment by drbraden** [comment]
The only issue I've found so far is a glitch with munin.  If I drill down into the graphs (it doesn't matter which metric) I get to a page where I should be able to create a custom graph but the image is broken:

![Imgur](http://i.imgur.com/vhXEHWN.png)

The URL of the missing image is ```https://box.example.com/munin-cgi/munin-cgi-graph/example.com/box.example.com/entropy-pinpoint=1435287911,1435395911.png?&lower_limit=&upper_limit=&size_x=800&size_y=400``` so it looks like it's having trouble running the munin-cgi-graph script (located at ```/usr/lib/munin/cgi/munin-cgi-graph```).

**Comment by dhpiggott** [comment]
I've just pulled and deployed 6441de63ba5a0d8d612183ee20cf6407ef46cf2e. It's the first time I've updated since v0.10.0!

@milani #247 is working nicely - I verified that relaying broke once I'd updated, and worked again once I added the appropriate catch-all aliases.

Thanks as always to you @JoshData and everyone who has contributed.

I'm still exploring the changes, but one thing I've just noticed is in relation to 47de93961e88d3790120caeece0648ed6ab2c44c. I was looking through the commits and on seeing this thought "mmm, interesting, perhaps I should do the equivalent in the configuration for my webserver".

So I read the article linked to in the commit message:
>Set ssl_stapling_verify to off per https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx ('on' has no security benefits).

But I couldn't find it suggesting `ssl_stapling_verify off` anywhere - the current example is:
```
ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /etc/sslmate/www.example.com.chain+root.crt;
resolver 8.8.8.8;
```

Then I noticed at the bottom:
>Updates
>2015-06-18: updated nginx instructions to enable OCSP stapling verification

So it would seem to me that SSLMate believe it *is* better to set `ssl_stapling_verify on`.

**Comment by dhpiggott** [comment]
I also do not get any dynamic Munin graphs. When I've used Munin via Apache in the past I seem to recall it being due to me not installing `libcgi-fast-perl`. But looking at management/daemon.py it looks like only the static files are proxied, so it's not surprising dynamic graphs can't be accessed.

I wouldn't really know where to start with ensuring the Munin CGI component is working and then making the management daemon proxy requests to it, but just thinking out loud, perhaps a simpler option would be to just configure Munin not to link to the dynamic graphs at all so the fact they don't work (read as "we don't support them") isn't accidentally discovered.

(For the avoidance of doubt the pages I'm talking about have locations of the form https://elm.dhpiggott.net/admin/munin/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=dhpiggott.net/elm.dhpiggott.net/diskstats_iops/xvda&size_x=800&size_y=400&start_epoch=1435294512&stop_epoch=1435402512.)

**Comment by JoshData** [comment]
@drbraden: Hmm. I didn't even know that was there. We're publishing the munin site as static pages. There's no support in our setup for executing a backend script for munin. Can you open a separate issue? (It won't block the release of v0.11.) (Crossed-wires with @dhpiggott's explanation above.)

@dhpiggott: Nice catch. I've reverted the change to ssl_stapling_verify. When I read that doc it discussed how the directive was unnecessary. I may ask the sslmate guy what changed.

**Comment by dhpiggott** [comment]
Sounds good re. ssl_stapling_verify. I'd be interested to know what you learn if you do ask.

FWIW, my box does still appear to include OCSP responses when I test it, both with openssl s_client and ssllabs.com.

Extract:

```
....
verify error:num=20:unable to get local issuer certificate
verify return:0
OCSP response: 
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: 90AF6A3A945A0BD890EA125673DF43B43A28DAE7
    Produced At: Jun 26 17:00:36 2015 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 7AE13EE8A0C42A2CB428CBE7A605461940E2A1E9
      Issuer Key Hash: 90AF6A3A945A0BD890EA125673DF43B43A28DAE7
      Serial Number: D8520DC304DCEA5155824C3F2C8CA28B
    Cert Status: good
    This Update: Jun 26 17:00:36 2015 GMT
    Next Update: Jun 30 17:00:36 2015 GMT
...
```

**Comment by drbraden** [comment]
@JoshData To be honest, I didn't know it was there, either.  I was just clicking things all over the place to see if I had any obvious breakage and that's where I ended up :)

But ya, no problem, I'll create a separate issue for it.  The good news is that I got it work on my box, so I'll include the steps I had to take in the new issue.

**Comment by PortableTech** [comment]
Any chance we could add in this PR before you issue 0.11, it is pretty minor in the grand scheme of things.

https://github.com/mail-in-a-box/mailinabox/pull/463/files

**Comment by JoshData** [comment]
@PortableTech No sorry I have some comments to make over there.

Version 0.11 is posted. Thanks all.
