### ISSUE TITLE
[Enhancement] Allow Self-Signed SSL certificates but warn users.

### ISSUE THREAD

**Issue by NurdTurd** [mail-in-a-box/mailinabox#552]
Allow a self-signed ssl certificate to be installed but warn people that they should still install a proper cert.

**Comment by brykov** [comment]
Is it really an issue since there are free certs on the market?

**Comment by MeltedLux** [comment]
You shouldn't be forced to get a certificate from the broken CA trust system. Many companies trust their own self-signed certificates on their devices.

**Comment by JoshData** [comment]
In that case, the admin can install the company's self-signed CA into the box's trust store (the CA would be self-signed, but the installed certificate would not, and should not, be).

**Comment by anoma** [comment]
I agree but we need to do more to instruct users how to get a cert i.e make it less scary with stronger recommendations on which free option to choose so that they dont all have to go away and do the same google searches and reading.

This is by far the hardest step in the MIAB install process for new users, everything up this point is relatively trivial.

Also keep in mind free certs are usually limited quite restrictive and  time limited.

I also suspect it is typical for users to be bringing a bunch of vanity domains to each install, each one adding to the SSL workload.

Then consider that mail works out of the box with self signed with perhaps one warning per client install about self signed but conversely you cant do this with your www site users.

The whole SSL ecosphere needs work, we are just yet another victim of it.

**Comment by JoshData** [comment]
I hope we can just have it be automatic using letsencrypt and we can drop this whole thing. :)

**Comment by NurdTurd** [comment]
@JoshData If you'd like I can make super simple straight to the point 1-2 minute tutorial videos.

**Comment by anoma** [comment]
letsencrypt updated schedule

>    First certificate: Week of September 7, 2015
 >   General availability: Week of November 16, 2015

@NurdTurd sounds like a great idea anyway just everyone is expecting letsencrypt to be a game changer

**Comment by NurdTurd** [comment]
I know I saw it already. Super excited for it! Every day I check the date and go "Aww come on already!". I am an active observer on the GitHub page. But I really would like self-signed certs to be installable.

**Comment by AngeloG** [comment]
So any update on allowing this? Currently an error is shown that "self-signed certificates can't be installed", even though the certificate is signed by a (self-signed) company root CA.

Letsencrypt support would be even better :)

**Comment by JoshData** [comment]
I'm not planning on fixing this, per my comment above.

**Comment by JoshData** [comment]
Now that let's encrypt is supported #268, this is no longer useful.
