### ISSUE TITLE
SFTP support for backups.

### ISSUE THREAD

**Issue by Hoekynl** [mail-in-a-box/mailinabox#553]
Please add support for the backups to be uploaded to a location using SFTP.

Example : Box > Home NAS. Feels safer than on the box, and safer than Amazon S3.

**Comment by dhpiggott** [comment]
The following may or may not interest you as an idea:

I mirror my box's backup directory to another VPS via a cron job on that other VPS that just runs rsync (set to run a couple of hours after MIAB's daily job runs). I also have that VPS email me the output of that cron job. The email then prompts me to rsync from the mirror VPS to my laptop - or, in the event that something goes wrong, I'll see that in the mailed cron output.

Key to this is that my MIAB does not push its backups anywhere - instead, they are pulled.

There are two advantages to this approach for me:

1. There is a security advantage in that it does not require that I authorize my MIAB to access my archives/backups VPS, so a compromise of the MIAB doesn't compromise the archives/backups VPS. I have my archives/backups VPS pull all the backups it mirrors - only my laptop has SSH access.
1. It is possible with MIAB as it already is, without modification.

**Comment by NurdTurd** [comment]
@dhpiggott you got to show me how to do that in a detailed manner.

:+1: +1 for SFTP backup support.

**Comment by dhpiggott** [comment]
@NurdTurd  I've observed that my MIAB's daily backup runs sometime just after 8am UTC, so on my backups VPS I have this in my login's crontab (edit with `crontab -e`):

``` 09 * * * ~/Backup/backup.sh```

The content of `backup.sh` is:

```
#!/bin/bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
rsync --archive \
    --human-readable \
    --delete \
    --delete-delay \
    --partial \
    --progress \
    --rsync-path='sudo rsync' \
    elm.dhpiggott.net:/home/user-data/backup/ $DIR/elm.dhpiggott.net/
rsync --archive \
    --human-readable \
    --delete \
    --delete-delay \
    --partial \
    --progress \
    --rsync-path='sudo rsync' \
    maple.dhpiggott.net:~/Backup/ $DIR/maple.dhpiggott.net/
```

(The second command pulls in backup files created by Duplicity on my web VPS.)

For something like this to work the login on the backup VPS naturally has to have an SSH key that's authorized on the backup sources, and the login on the sources needs to be setup for passwordless `sudo`.

I said that I get the output of these jobs emailed to me. As an example of what that looks like, here is yesterday's output (today's was particularly voluminous due to my webserver having done a new full [as opposed to incremental] backup):

```
receiving incremental file list
cache/77bb3fb2afb5975d26aa819871b4bd44/
cache/77bb3fb2afb5975d26aa819871b4bd44/duplicity-inc.20150914T065114Z.to.20150915T063620Z.manifest

              0   0%    0.00kB/s    0:00:00  
            216 100%  210.94kB/s    0:00:00 (xfr#1, to-chk=708/888)
cache/77bb3fb2afb5975d26aa819871b4bd44/duplicity-new-signatures.20150914T065114Z.to.20150915T063620Z.sigtar.gz

              0   0%    0.00kB/s    0:00:00  
        235.92K 100%    1.49MB/s    0:00:00 (xfr#2, to-chk=535/888)
encrypted/
encrypted/duplicity-inc.20150914T065114Z.to.20150915T063620Z.manifest.gpg

              0   0%    0.00kB/s    0:00:00  
            243 100%    1.56kB/s    0:00:00 (xfr#3, to-chk=174/888)
encrypted/duplicity-inc.20150914T065114Z.to.20150915T063620Z.vol1.difftar.gpg

              0   0%    0.00kB/s    0:00:00  
          2.85M 100%    3.54MB/s    0:00:00 (xfr#4, to-chk=173/888)
encrypted/duplicity-new-signatures.20150914T065114Z.to.20150915T063620Z.sigtar.gpg

              0   0%    0.00kB/s    0:00:00  
        236.39K 100%  298.64kB/s    0:00:00 (xfr#5, to-chk=0/888)
receiving incremental file list
data/
encrypted/
encrypted/duplicity-inc.20150914T070013Z.to.20150915T070013Z.manifest.gpg

              0   0%    0.00kB/s    0:00:00  
            229 100%  223.63kB/s    0:00:00 (xfr#1, to-chk=31/102)
encrypted/duplicity-inc.20150914T070013Z.to.20150915T070013Z.vol1.difftar.gpg

              0   0%    0.00kB/s    0:00:00  
        323.18K 100%    1.33MB/s    0:00:00 (xfr#2, to-chk=30/102)
encrypted/duplicity-new-signatures.20150914T070013Z.to.20150915T070013Z.sigtar.gpg

              0   0%    0.00kB/s    0:00:00  
          3.38M  39%    3.22MB/s    0:00:01  
          7.96M  92%    3.80MB/s    0:00:00  
          8.64M 100%    3.95MB/s    0:00:02 (xfr#3, to-chk=0/102)
```

As cron emails output of jobs to their owner by default, I just had to make sure the VPS was setup to be able to deliver mail. So I installed Postfix on the backup VPS (choosing the full configuration option during install). I did this instead of setting up relaying as documented at https://mailinabox.email/advanced-configuration.html#relay because I want the backup VPS to be as loosely connected as possible in terms of configuration from my other machines. The first deliveries were naturally subject to greylisting but after that they get through instantly.

Then to make sure that mail makes its way to my normal mailbox I set that as the destination in the `.forward` file of my home directory on the backup VPS:

```
david@cedar:~⟫ cat .forward 
david@piggott.me.uk
``` 

This bit isn't strictly necessary but I also set it up so mail sent to root (e.g. failed login attempts) makes its way to my user and thus by transitivity of the `.forward` to my normal mailbox:

```
david@cedar:~⟫ cat /etc/aliases
# See man 5 aliases for format
postmaster:    root
root:          david
````

(run `sudo newaliases` after editing `/etc/aliases`).

**Comment by Hoekynl** [comment]
I understand there are other methods for the SFTP backup method. But I am just a user which does not have alot of experience with ubuntu (I have a little bit of knowledge about it) and would like to see an easy option : Server, Port, Username, Password (maybe even what time to backup?)
This would be easier for other users aswell

**Comment by NurdTurd** [comment]
@dhpiggott thanks for the in-depth explanation I really appreciate it. :)

**Comment by NurdTurd** [comment]
:+1: +1 for SFTP backups.

**Comment by NurdTurd** [comment]
Or maybe even rsync backups could be put into MIAB ? :smile:

**Comment by NurdTurd** [comment]
@dhpiggott I work in system administration, so I can read bash scripts pretty quickly. Very nicely formatted. Thank you for the help. The only issue I was wondering about was email and on how to send it. That's all. Again, thanks so much. :smile:

**Comment by hadifarnoud** [comment]
@dhpiggott I need to pipe emails via /etc/aliases on MIAB. I saw you used it here. 

Did you have to do anything else on top of `newaliases` afterwards? is it better to use .forward?

below is my /etc/aliases content
```
# See man 5 aliases for format
postmaster:    root
support: "|/bin/sh /root/post-mail http://support.camva.ir/tickets.json"
```

sorry for hijacking your issue.

**Comment by JoshData** [comment]
[comment above deleted because it was off topic]

**Comment by JoshData** [comment]
moving discussion to #717
