### ISSUE TITLE
PositiveSSL Installation

### ISSUE THREAD

**Issue by josemejiasji** [mail-in-a-box/mailinabox#564]
Hi, 

I can't install my PositiveSSL certificate. I'm adding my domain cert and the intermediate chain in this order:

COMODO RSA Domain Validation Secure Server CA
COMODO RSA Add Trust CA
Found here: https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/979/108/domain-validation-sha-2

I also tried with the sha-2 bundle found in the COMODO downloads section

https://github.com/mail-in-a-box/mailinabox/wiki/FAQ

But MiaB is ALWAYS returning:

<img width="594" alt="captura de pantalla 2015-09-28 a las 1 42 00" src="https://cloud.githubusercontent.com/assets/630925/10125820/66f43cd0-6582-11e5-946e-dca1ccfe13a5.png">

What should I do?

Regards.

**Comment by jerogee** [comment]
Jose, it is very unlikely that this is a MIAB bug. I also use a Comodo certificate, and the certificate order you indicated is correct.

The second most likely reason, also indicated by the error message, is that the server certificate and the  first certificate of the intermediate chain do not match.

MIAM auto-generates a private key with a Certificate Signing Request (CSR) that needs to be given to your certificate provider. Are you sure that you provided that CSR to your certificate provider in order to obtain your SSL certificate? 

If you are not sure, I would first check if the CSR by MIAM and your certificate were based on the same private key. To do this, [you could use this tool](https://pkiwidgets.quovadisglobal.com/pkiwidgets/matchCertAndCSR.aspx) (n.b. NEVER use online tools that ask for your private key as well).

If they are not based on the same private, it means that you either used a CSR that you manually generated from a private key yourself, or your certificate provider generated a private key + CSR for you (happens with some providers when no CSR is entered). WHEN the certificate you have is indeed not based on MIAB's CSR, the cheapest solution is to SSH into your box and replace the private key that MIAB so helpfully auto-generated with whatever private key that was used to base the Comodo certificate on.
