### ISSUE TITLE
Install at primary domain (e.g. example.com) rather than subdomain (e.g. box.example.com)

### ISSUE THREAD

**Issue by brylie** [mail-in-a-box/mailinabox#568]
What are the risks of installing this project at the primary domain (e.g. example.com) as opposed to the box subdomain (e.g. box.example.com)? 

Our domain registrar (Namecheap) does not allow us to set up custom nameservers as sub-subdomains (e.g. ns1.box.example.com). Can we just use example.com for the installation and ns1.example.com for the nameserver configuration?

**Comment by nstanke** [comment]
I used ns1.box.example.com just fine at Namecheap.

**Comment by brylie** [comment]
OK, well they changed their panel lately, and I am unable to configure a sub-subdomain. I chatted with a tech support there, but they said it is not possible.

**Comment by brylie** [comment]
Additionally, we might want to install at the primary domain, so tha we don't have to manage multiple certificates.

**Comment by nstanke** [comment]
I'm sorry, I never tried to setup MiaB on the root domain.

**Comment by JoshData** [comment]
You can use the primary domain just fine, but it is a less flexible setup because then you cannot point the website on that domain to another server if you want to use the domain for a nice website beyond static pages (= the DNS A/AAAA records have to point to the box).

**Comment by brylie** [comment]
Ah, I was wondering about the limitations,. Thanks @JoshData. Itmight be worth setting it up at the main domain, and then using sub-domains for possible additional websites in our case.

**Comment by acicali** [comment]
Sorry for the necropost, but I just tried installing at the root domain and it doesn't seem to install correctly. With box.domain.com everything worked flawlessly, but when I started over with just domain.com the web interface no longer offers the "Provision" button for generating certs.

**Comment by acicali** [comment]
Sorry for the necropost, but I just tried installing at the root domain and it doesn't seem to install correctly. With box.domain.com everything worked flawlessly, but when I started over with just domain.com the web interface no longer offers the "Provision" button for generating certs.

*Edit*: I deleted this post because I realized that this might be due to glue records, but I've ruled that out. It seems like the installation does not create an A record for the root domain if installed without a subdomain, and then because of that no certs are generated.
