### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#575]

**Comment by JoshData** [comment]
So, in principle this is a good idea. The problem is that it introduces a dependency on a large number of humans to do translations prior to each update. If a language becomes unsupported because a translator doesn't do the work promptly, then a release can't be made without dropping support for a language, which would be very inconvenient for users.

**Comment by aspdye** [comment]
I could do this promtly (for German)

**Comment by JoshData** [comment]
You say that today, but what about 2 or 4 years from now?

**Comment by aspdye** [comment]
Then you can use Google Translator :D :D ...yeah...i know that that could be a Problem.

**Comment by dhpiggott** [comment]
Rather than delay the release of updates by blocking on pending translations, updates could be released despite outstanding translations --- instead just showing the English strings for those that haven't been translated. So on upgrade users of the language would find that their experience goes from 100% localised to (e.g.) 95% localised; no need to throw the baby out with the bathwater by dropping the language entirely.

Then, when the missing 5% translations are provided, a patch release (in the sense of semver.org) could be issued, bringing things back to 100%. Cunningham's Law may apply here too in that other users of the language might volunteer translations when they encountered the untranslated strings.

A language would be dropped only if coverage became and remained incomplete for several consecutive releases.

And hopefully issuing partially translated releases wouldn't be necessary for most releases anyway because translations would be requested/provided on a per change basis rather than leaving them all until just before a release.

**Comment by aspdye** [comment]
Or would you rate the new version anyway release it, and the other languages populating as "unofficial".

Languages can also be interesting if we move the autoresponder-settings, password etc. from Roundcube to the Admin Panel, because the users are even more dependent on their native language, as the Admin. (As I propose, among other things in # 606).

**Comment by guyzmo** [comment]
Actually, translations (like documentation) is the best way to get less technical oriented people contribute and feel great at participating in the project. To make it easier for everyone to translate the application, there's a bunch of services that exists to handle the gettext strings:

- http://pootle.translatehouse.org/index.html
- http://zanata.org/
- https://poeditor.com/
- https://www.transifex.com/

But as a first step doing that, we can first `_()` all the internal strings. For the HTML templates, we can either use different sets of pages templates, or use some javascript framework (i18next or polyglot.js) to handle translation within the template. We might want the second option, to keep only a single set of pages, and use the english strings as keys for the translations.

**Comment by guyzmo** [comment]
BTW, I can start the french translation as well ;-)
