### ISSUE TITLE
Configure Backup Time - Clients all knocked offline during backup!

### ISSUE THREAD

**Issue by Futurama56** [mail-in-a-box/mailinabox#577]
* How can we configure the time at which a backup is triggered?
* All our users get disconnected during a backup period, even for a few minutes - but with people around the world, we're getting plenty of "negative" feedback about disconnects, and server unavailable. 

 What is your proposed solution to backup without disconnecting users?  Surely as other users scale your application - they will run into this issue as well.

**Comment by nstanke** [comment]
Good point. I guess we could leave Dovecot running if we would use doveadm-sync[1] to create a backup?

[1]http://wiki2.dovecot.org/Tools/Doveadm/Sync

**Comment by Futurama56** [comment]
This is a real problem we have - so would love to integrate a solution!  Thanks guys

**Comment by JoshData** [comment]
The backup is run via cron.daily, and if you can figure out how to change that time, that'll solve it for now.

Like everything else, I'd really like it to "just work." It would be neat if it looked at the logs to see the time when the box is in least use (fewest outbound emails, perhaps) and then set the backup time to that.

**Comment by Futurama56** [comment]
"Like everything else, I'd really like it to "just work." It would be neat if it looked at the logs to see the time when the box is in least use (fewest outbound emails, perhaps) and then set the backup time to that."

This doesn't seem to solve the issue - that you shut down all services to the mail server when performing a backup, thus disconnecting clients and causing pandemonium.

**Comment by JoshData** [comment]
@nstanke's alternative means making a clone of all of the mailbox content, which means needing lots of extra disk space. This is how backups used to work (coincidentally --- it wasn't because of avoiding restarting services, but because of how I set up `duplicity`). But no one liked having to have twice as large a hard drive as they would have otherwise needed, so we rewrote the backups to avoid that.

We can probably skip shutting off `postfix` without any issues.

But if we don't shut down `dovecot`, we risk making a backup of the mailboxes directory in an inconsistent state. Unless we attempt to lock the mailboxes, but I don't know how dovecot will respond if mailboxes are externally locked for a few minutes (or more).

If you have other ideas, let me know.

**Comment by nstanke** [comment]
@JoshData 

We could check if a bit more than double the mailbox size of disk space is free, then do a "hot backup" without downtime. If not we fall back to the current system.

 Thoughts about that?

**Comment by JoshData** [comment]
Yeah that's an interesting idea. I like it. There are a few issues that we might just ignore.

* The directory of mail that the backup sees will be different depending on which method is used (mail/mailboxes vs a directory that holds a clone). So if a box is hovering right on the free-disk-space line between the two methods, the incremental backup may switch back and forth each night between the two methods --- that won't be friendly to increments.

* Similarly, the restore process will be slightly more complicated because mailboxes won't be in the right place.

* Making a clone of a large mailbox is still possibly going to be slow and compute-intensive (even with dovecot tools).

* We know from #531 that computing the size of mailboxes is very slow for large mailboxes, so making the determination of which method to use may itself be IO-intensive.

**Comment by haraldkoch** [comment]
Since MIaB already require a "clean" Ubuntu 14.04 installation, how about requiring a snapshot-capable filesystem, at least for mailboxes?

Just a thought...

**Comment by JoshData** [comment]
That's an interesting idea. Tell me more.

**Comment by haraldkoch** [comment]
Oh bother. Some quick googling later, and it appears that:

* none of the stable Linux filesystems support snapshots
* the two filesystems that do, ZFS and btrfs, are not production ready
* LVM is supposed to be an alternative, but LVM snapshots are buggy and not recommended

This surprises me, but I guess we're all using hypervisor snapshots instead of filesystem snapshots these days. So - just ignore me...

**Comment by yodax** [comment]
I believe ZFS the filesystem is stable enough. Also since 2014 it could be considered production ready on Linux. The system it self make sure there is no data corruption. The Linux modules where it bit slower in the last benchmark I saw. When I saw this discussion I thought of ZFS (I am mostly a FreeBSD user), I thought it wouldn't work because of the increased system requirements, for me at least. It would raise the cost of hosting.   

Production readiness sources:

http://www.phoronix.com/scan.php?page=news_item&px=MTc4NTM
https://clusterhq.com/2014/09/11/state-zfs-on-linux/

Memory requirements:

http://zfsonlinux.org/faq.html#BasicRequirements

It recommends 8GB minimum, however: The ZFS devs for FreeBSD and OpenZFS have mentioned that this was true for early versions. However nowadays it can cope with less. If you want performance ZFS thrives with memory.

On my 16GB home server it likes to consume:
ARC: 12G Total, 5271M MFU, 4663M MRU, 7712K Anon, 153M Header, 1817M Other

**Comment by OmgImAlexis** [comment]
@haraldkoch keep in mind a lot of people use things like DigitalOcean and may not be able to switch as easily as you'd think. [ZFS is possible](https://2bithacker.github.io/hackery/2015/02/16/zfs-on-a-freebsd-droplet/) on there though so it may be possible on other cloud providers too.

**Comment by bronson** [comment]
> We know from #531 that computing the size of mailboxes is very slow for large mailboxes

That's true if you're computing directory-level utilization (`du`).  For example, if you're computing per-user disk usage.

For this, though, you only care about filesystem-level utilization (`df`).  And that's always basically instantaneous.

**Comment by JoshData** [comment]
Now that we set the system timezone, and backups are tied to a time in that timezone, do we need anything else here?
