### ISSUE TITLE
5.7.1 "Not owned by user" error with secondary domains.

### ISSUE THREAD

**Issue by 0x27** [mail-in-a-box/mailinabox#578]
Hey,
So I added some more domains pointing at my MailInABox (set it as the nameserver, for them, etc). Those email addresses recieve emails just fine.

However, they are not capable of sending email, as per following log.

```
Oct 20 09:49:41 box postfix/submission/smtpd[24057]: connect from unknown[193.1.x.x]
Oct 20 09:49:41 box postfix/submission/smtpd[24057]: NOQUEUE: reject: RCPT from unknown[193.1.x.x]: 553 5.7.1 <email@secondary.domain>: Sender address rejected: not owned by user adminuser@primary.domain; from=<email@secondary.domain> to=<redacted@mygmailaccount.com> proto=ESMTP helo=<[10.12.11.49]>
Oct 20 09:51:24 box postfix/submission/smtpd[24057]: lost connection after RCPT from unknown[193.1.x.x]
Oct 20 09:51:24 box postfix/submission/smtpd[24057]: disconnect from unknown[193.1.x.x]
```

I am unsure what is happening here, having followed the setup guide pretty much to the letter. Any ideas? The MX is behind a NAT, with the SMTP, IMAP and DNS ports forwarded, if that makes any difference.

**Comment by dhpiggott** [comment]
Mail-in-a-Box checks the user that you are logged in as when attempting to send against the alias you are trying to send as.

In this case it's checking that adminuser@primary.domain has permission to send as email@secondary.domain, and rejecting the send attempt because it doesn't.

You'll need to grant permission to adminuser@primary.domain by adding it to the "permitted senders" list associated with email@secondary.domain in the Mail > Aliases control panel.

The reason Mail-in-a-Box requires that you grant these permissions is to prevent sender spoofing as identified at https://github.com/mail-in-a-box/mailinabox/blob/master/security.md#user-policy.

**Comment by 0x27** [comment]
Heh, I just realized my screw up. In my mail client it was using the primary domain accounts settings for the secondary one, causing the user impersonation issue. Its always the simple things that I miss.

Thanks :)
