### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by atrotossavainen** [mail-in-a-box/mailinabox#58]
How does one restrict delivery to the Mailinabox with a quota? I'd like to make sure that the limiting factor happened earlier than the actual physical disk space in the instance because systems have an annoying tendency to crash if you allow the disk space to become full.

**Comment by aspdye** [comment]
Any news here?

**Comment by ViktorEyermann** [comment]
Any news?

**Comment by JoshData** [comment]
No news until someone does the work....

**Comment by aspdye** [comment]
Quota implementation is already working. Thank you @rainulf :sunglasses: 
Looking forward to the merge of @JoshData !

**Comment by aspdye** [comment]
Can we remove the "needs volunteer" label please ;)

**Comment by pryley** [comment]
If anyone wants to try the quotas feature on v0.20, I have merged @rainulf's changes to a fork of the latest master commit [da5497c](https://github.com/mail-in-a-box/mailinabox/commit/da5497cd1cce54e4601d616e333de98b04b95d2e):

SSH into your box and then:
```
$ git clone https://github.com/geminilabs/mailinabox mailinabox-quotas
$ cd mailinabox-quotas
$ git checkout feature/quotas
$ sudo setup/start.sh
```

**A few things to note:**

1. This worked/works fine on my existing v0.20 box, but as always make a backup. If you use DigitalOcean, make a snapshot of your droplet before upgrading. Use at your own risk.

2. Quotas is a great feature for the server admin to curb disk space usage, but it's not so user friendly for the user. If the user quota is full and they are using an email client to sync their emails, they will get no notification that they have run out of quota space and they will not realize that emails being sent to them are getting returned to the sender.

3. Instead of implementing quotas, consider hosting on DigitalOcean and using a datacenter that supports Volumes. $0.10 per GB per month. https://www.digitalocean.com/products/storage/

**Comment by mitchellurgero** [comment]
Is this going to be implemented in the near future? Would love to see quotas :)

**Comment by pryley** [comment]
@mitchellurgero I don't think quotas will be ever be officially implemented. I suggest if using DigitalOcean, host your mail server 💧 on a server that supports Volumes. Working great over here, 50 GB volume for $5/month. You can choose a smaller volume size and grow as needed.

**Comment by mitchellurgero** [comment]
Can I at least install this modification on the latest 0.21?

**Comment by mitchellurgero** [comment]
Also, thanks for the response, but I will be hosting over 100 emails, and would like to limit each account specifically. :)

**Comment by yodax** [comment]
>Can I at least install this modification on the latest 0.21?

The PR has merge conflicts.

Also it changes the layout of the database: https://github.com/mail-in-a-box/mailinabox/pull/665/files#diff-d55d822b8e6ccfbe30985a32aeaca9c6

So even if it might be mergeable for 0.21, it might not be for 0.xx. So if your are not comfortable with applying the patch set  every time and possibly dealing with database layout changes, then no. Also if quota's do land, it might be a different implementation and you would have to provide an upgrade path yourself.

**Comment by guyzmo** [comment]
I personally don't need it, but quota is a safe and simple feature (postfix/dovecot that can be integrated with little friction. In terms of UI, it's only a question of adding a numeric input box, and the database update (which has to happen once).

So the real question, @JoshData what do you think needs to be done to make this PR 👌 to merge?

**Comment by JoshData** [comment]
Solve one of the more pressing issues first (e.g. #514, #777, among others)  and then we can talk about adding features!

**Comment by rainulf** [comment]
PR is here #665 - I rebased it, and resolved conflicts. But it's not tested, because I currently don't have time.

I am fairly out to date with the state of this project, but I do still use mailinabox. Implementation of quota is simple, but it is really up to the maintainer which priority to take, or if this feature is even necessary.

**Comment by mitchellurgero** [comment]
for #514 - One option is Pydio. It has an open source version (I dont remeber the license it uses) but would be "simple" enough to swap out as it also supports SQLite.

**Comment by JoshData** [comment]
@mitchellurgero Can you re-post that in that issue instead of here?

**Comment by laupkram** [comment]
what is the status of this PR? this is a very good feature :)

**Comment by JoshData** [comment]
Solve one of the more pressing issues first (e.g. #514, #777, among others) and then we can talk about adding features!

**Comment by tynie** [comment]
Any news?

**Comment by othaner** [comment]
Is there any news on this feature? Or anyone knows how to do this? Thank you

**Comment by kendall1997** [comment]
Any news on 2022?

**Comment by joyvw** [comment]
Any news on 2024 ?
