### ISSUE TITLE
Please test the v0.14 release candidate

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#582]
The `master` branch is now a release candidate for v0.14.

If you are able, and if you see this, I'd appreciate help testing. If you try the master branch, please post here if it works ok or not. Thanks!

There is a fairly significant change under the hood in how SSL certificates are selected for use by the non-primary domains for https. It used to be that non-primary domains would get an automatically generated self-signed certificate at first, and then an installed certificate would replace the self-signed certificate file in `STORAGE_ROOT/ssl/domainname/ssl_certificate.pem`. Now for non-primary domains, Mail-in-a-Box scans the whole `STORAGE_ROOT/ssl` tree for valid certificates and applies the best certificate it can find to each domain. If it doesn't find one, it uses the system's main certificate (for the primary hostname). So.... be on the lookout for any issues with that.

**Comment by yodax** [comment]
I have moved my main domain over to the new version. Installation went fine (as always). All the UI elements seem to work (Status/DNS/SSL/Munin/Roundcube/OwnCloud). Also my devices still connect.

Will let you know if I run in to issues.

Thanks for the hard work!

**Comment by dhpiggott** [comment]
I just deployed master (720157e8a3ee56e0643f808508781d34dc2e107f) to my box.

My experience is much the same as @yodax's -- installation was fine and I've not found any regressions.

One thing I am curious about is the status checks. I did quickly scan through the changes and so made a note to look out for the new secondary nameserver checks (3b91bc2c0a33eee8bb3feaa44f4f7c5747e34949). I haven't reviewed that change (yet) to the point that I know exactly what I should expect in the status checks now, but at first glance it made me expect to see an item in the checks containing the string "Secondary nameserver...". But I do not see anything in my box's status checks about secondary nameservers (my box's secondary nameserver is set -- to `ns6.gandi.net`). Perhaps I'm wrong to expect anything in the checks when things are setup correctly. But I thought I'd mention it in case I should be seeing something. I may review 3b91bc2c0a33eee8bb3feaa44f4f7c5747e34949 later to ensure my expectations are correct.

As always, thanks all for the careful work!

**Comment by dhpiggott** [comment]
I looked into the secondary nameserver check and now understand why I don't see anything new in my box's status checks.

It's because *all* of the names hosted by my box (except for the primary hostname itself) have their A records point to another IP (my web VPS). So the condition at https://github.com/mail-in-a-box/mailinabox/commit/3b91bc2c0a33eee8bb3feaa44f4f7c5747e34949#diff-ef8d327c062a6248bba01da4aba89da7R406 is not met for any of the calls to `check_dns_zone`. And the primary hostname itself is checked by `check_primary_hostname_dns`, so there's no new output for `elm.dhpiggott.net` either.

The comment on the unmet condition is `If the user is probably not using external DNS...`.

Is the condition `if ip == env['PUBLIC_IP'] and custom_secondary_ns` the best heuristic for that? What about querying a public DNS server (e.g. Google DNS) to determine whether the box is actually set as the primary nameserver?

**Comment by JoshData** [comment]
Good call, fixed!

**Comment by dhpiggott** [comment]
Nicely fixed. I just pulled and deployed it -- the check runs now.

**Comment by yodax** [comment]
I started using Gandi as a secondary DNS this morning since I want to move my *.nl domains to Gandi as wel. I currently have a few other domains that previously worked with a single dns server managed by the box.

So my situation now is:

+ Multiple domains handled by mailinabox, with a secondary dns at Gandi
+ Multiple domains handled by external dns (pending a move to Gandi)

The status check for the domains handled by mailinabox is ok:

<img width="583" alt="schermafbeelding 2015-11-03 om 15 28 10" src="https://cloud.githubusercontent.com/assets/5643940/10910410/97bac602-823f-11e5-8115-a53a8209ad77.png">

The status check for the domain not handled by mailinabox shows an error:

<img width="869" alt="schermafbeelding 2015-11-03 om 15 29 46" src="https://cloud.githubusercontent.com/assets/5643940/10910444/bf18bc0e-823f-11e5-9de0-aa6ff3736206.png">

While the error is correct. The system already detects that the domain isn't controlled by the box here https://github.com/mail-in-a-box/mailinabox/blob/3fd1279e7dc16da3e4b7be4da926bf3ab0ff6cbb/management/status_checks.py#L402-L404. 

If we store the result from that check and use it to mark the messages as warnings instead of errors here: https://github.com/mail-in-a-box/mailinabox/blob/3fd1279e7dc16da3e4b7be4da926bf3ab0ff6cbb/management/status_checks.py#L425
It would reflect the status better I think. 

Also I have pulled all the latest commits and everything is still working fine.

**Comment by JoshData** [comment]
Thanks guys! The release is now posted. @yodax Let's leave this issue open until that's fixed. (I didn't want to hold up the release for it.)

**Comment by yodax** [comment]
No problem. And thank you! The quality of this project is top notch. Good documentation, wel structured making it easy to jump in and start using/contributing.

**Comment by JoshData** [comment]
Thanks!

**Comment by yodax** [comment]
Tested dns and can confirm, both situations work.

**Comment by JoshData** [comment]
Thanks for checking!
