### ISSUE TITLE
Dockerisation #2

### ISSUE THREAD

**Issue by pierreozoux** [mail-in-a-box/mailinabox#590]
## Introduction

(following discussion from https://github.com/mail-in-a-box/mailinabox/pull/338 and https://github.com/djmaze/mailinabox-docker/issues/3)

A lot of people would like this project dockerized. Actually it could be the future way of installing miab (without dependency to ubuntu LTS as a platform, but this is another discussion).

With @djmaze, we are willing to spend resources on this matter.
(he did https://github.com/djmaze/mailinabox-docker, and I'm working on https://github.com/indiehosters/email, and we are discussing on converging our work)

We agreed that a multi container setup is more appropriate as a one container for everything (like the first dockerisation try). The advantage of this, it could be that some people will be able to use just postfix for instance.
I think if we do a good work, we could PR docker official repo for every services included in miab (ok, this is more a long term goal). But I believe we can have more people using miab if it is properly dockerised.

## Problem

The issue with our current try to dockerise is that it is difficult to maintain with upstream. Docker has its own philosophy, and it is difficult to put miab inside.

## First step

This [commit](https://github.com/mail-in-a-box/mailinabox/commit/acec82950b1afc58beb6d217231c2cf52db858e5) is already a huge win toward dockerisation.
But we believe that we should split main configuration from runtime configuration.
When it is done, it will be a lot easier to start to dockerise properly.

What do you think?

If you think it is a good idea, then we'll start to PR toward this direction.

**Comment by JoshData** [comment]
So I'll be honest, my experience with Docker over the last few years has been pretty negative. And for us,  it just doesn't seem to be very compatible with Mail-in-a-Box's goals of making it _easy_ to set up a system. Once multiple docker containers are involved, things get complicated fast. And Mail-in-a-Box only works by assuming a common base system of a complete Ubuntu 14.04 system, and that's a lot of what is hard to replicate in Docker.

Using multiple containers is also an extra challenge because it means throwing away a lot of what makes Mail-in-a-Box work. All of the system configuration that ties the services together might need to be rewritten into two versions, one for a single Ubuntu 14.04 system and one for a multi-docker system. And it would be really good to avoid that, because it means twice the effort to keep the project going.

Maybe something like [LXD](http://www.ubuntu.com/cloud/tools/lxd) would be more appropriate, but I haven't tried that.

Another thought - Rather than Dockerize first, it might be useful to think about how Mail-in-a-Box could be re-architected to have better separation between major system components. For instance, I now love setting up every new domain I buy with my Mail-in-a-Box because it makes sure I get DNS & web set up correctly --- even if I don't need mail on the domain. How might things work if the project were split into DNS-in-a-Box, Web-in-a-Box, and Mail-in-a-Box (with Mail-in-a-Box transparently depending on the first two).

**Comment by almereyda** [comment]
Once the separation takes place, advanced end users could also choose during installation if they need certain features. Therefore this sounds more like a task for Ansible or Puppet playbooks.

* DNS is definately a pro feature, but should at least be accompanied by a web interface like [fmDNS](http://www.facilemanager.com/modules/fmdns/) if to be taken seriously. Now it always bugs me MIAB tries to take over my (additional) zones (next to the hostname's with glue records) and I rather copy and paste the DKIM and DMARC settings manually instead of losing the ability to add further entries.
* Web hosting may be even discardable for most users who *only* want to have mail functionality + webmail.
* Mail then being the ideal combination of the former.

@pierreozoux But do you see how - by reaching out for broader user bases and cases - configurability leads to the introduction of new abstraction layers, which may be solved in other places already? Just thinking of Sovereign or Modoboa, but I'm sure there are others, too.

@JoshData as the maintainer:

> Which path would you prefer?

---

Containerization: LXD is a bit coupled to Canonicals infrastructure AFAIK. But one could abstract of course different containerization engines like CoreOS' rkt  (building on systemd-nspawn) or others.
Additionally, one may also want to research to use a different base OS.

**Comment by dhpiggott** [comment]
I've found that leaving MIAB to handle DNS is far easier than copying and pasting records over to third party DNS. If you use DNSSEC, copying and pasting records isn't a good idea because you'll need to manually copy changes over in a timely manner every time they're resigned -- which would surely go wrong quickly.

So I'd argue that *not* leaving MIAB to handle DNS is a pro feature because it's too easy to get things wrong that way.

What do you mean by "losing the ability to add further entries"? I leave my box to handle my DNS but have also customized a few records (I don't use MIAB for web hosting, instead having all my A records point to another box). I've yet to find a record I've wanted to customize that MIAB wouldn't let me change (not counting #229 which was over a year ago and was fixed the same day).

**Comment by pierreozoux** [comment]
Thanks for your reply ( @JoshData @almereyda and @dhpiggott ).
Seeing the discussion around DNS/Web/Mail/CardDAV/CalDAV in a box, looks like we'd need something really modular.

IMHO, we need great API between these services to interact.

AFAIK, there are 3 methods to "manage" interdependencies between software:
 - OS packages (yum/apt) - FreedomBOX path (didn't work much until now)
 - hand made scripts (relying on the underlying OS package) (MAIB/yunohost/arkos, if you know more, tell me ;) ) - successful 
 - containers (docker/rkt/lxc/lxd/runC...) (Clouder/IndieHosters/ if you know more, tell me also) - experimental / not successful (yet?)

And, so I think, we need great API, to let end user (in the sense of consumer of these APIs) decide which path to take, for each module. This way people could be free to choose their cardDAV backend no matter if it is in a container, on one single physical machine or provided by a VPS with MIAB installed.
So the API issue is almost solved. For the DNS, it is still missing, not widely available I would say. MIAB provides one, yunohost also I think, bind9 doesn't, powerDNS does...

So indeed the difficult bit is to tie services together, but this should be achieved by APIs, not obscure bash script we are all using :/

IMHO and a lot of people are predicting the same, the containers are the future. I believe it is a really convenient system to have a great abstraction to manipulate services the same way (no matter if inside is running DNS, php, python or mysql)

But let's get back to our greater goal (provide easy to use free software as a service for people).
We have limited resources, and not much people around the world are working full time on it.
I think we should try to collaborate.
How? I don't have a clue. Every tries I did failed (with @almereyda and others, we still didn't manage anything :/)

This is a big deal, isn't it? How many people out there have spend time to configure a postfix? This is something that makes me sad, we are wasting hours of precious time.

I'm not sure we'll find solution on this thread. This is more a bottle in the ocean now, than a concrete and well defined problem to solve.

@JoshData please feel free to change title and/or close the issue. If you have ideas, I'd be glad to hear :)

**Comment by pierreozoux** [comment]
And something more or less related: https://medium.com/enspiral-tales/doing-more-together-together-seeding-a-collaborative-technology-alliance-82243ea30d41

**Comment by almereyda** [comment]
I am very excited to read what has come to your mind above @pierreozoux . In the end, it is kind of our migration path from the Internet stack (SMTP, IMAP, XMPP, IRC) to a purely Web stack, ideally built on Activity Streams 2.0 and the likes.

We shouldn't try to repair E-Mail. In this sense, you way want to draw a line around your implementation, explicitly stating what you try to achieve. And yes, I am also favouring loosly coupled services over lously coupled snowflake servers.

**Comment by JoshData** [comment]
Closing because no one seems to be working on this and docker doesn't seem to have been the right approach. As in #112.

**Comment by anoma** [comment]
FWIW 

https://mailcow.email/dockerized/

have done an amazing job dockerizing in the way a few of us proposed, a series of containers linked in one bridged network.

This approach also lets you migrate to a solution daemon by daemon rather than a hail mary.

I still say it is the future for a appliance like OS like us.

**Comment by meglio** [comment]
Discourse is another great example of a complex application deployable through Docker. Indeed, their Docker container is the only official way to go.
