### ISSUE TITLE
How to uninstall mail in a box in Ubuntu 

### ISSUE THREAD

**Issue by rinodung** [mail-in-a-box/mailinabox#593]
Please tell me how to uninstall it from my Ubuntu VPS?

**Comment by dhpiggott** [comment]
There is no uninstaller, so I think you'll find it quicker and easier to reinstall Ubuntu than trying to manually revert each change made by Mail-in-a-Box.

**Comment by geneowak** [comment]
You can actually 'uninstall' it (remove would be a better word).

I happened to install it on a server that we were using already and it messed up some of the domains we had and so I had to get rid of it and install it on a new server. Reinstalling Ubuntu wasn't an option since the server already had many things. I did a little search and came across a way of removing it without refreshing the server.

#### Here are the steps that worked for me.

1. Delete the `mailinabox` directory.
2. Rename the `/etc/nginx/conf.d/local.conf` to `/etc/nginx/conf.d/local.conf.old`
3. Rename the `/etc/nginx/conf.d/ssl.conf` to` /etc/nginx/conf.d/ssl.conf.old`
4. Reload nginx `systemctl reload nginx`.

You can also rename the server by updating the `/etc/hosts` and `/etc/hostname` files

checkout this [medium post](https://medium.com/@mykeels/how-to-uninstall-mail-in-a-box-8081c6e718bc)

**Comment by dellnoantechnp** [comment]
I try to uninstall and clean mailinabox project, under there:
```shell
rm -rf /home/user-data/*
rm -rf /var/lib/mailinabox/
rm -rf /var/cache/munin/
rm -rf /usr/local/lib/mailinabox /usr/local/lib/roundcubemail  /usr/local/lib/z-push
rm -rf /usr/lib/systemd/system/mailinabox.service
rm -rf /usr/lib/systemd/system/munin.service
apt remove fail2ban --purge -y
apt remove munin-node munin --purge -y
apt remove opendkim opendmarc --purge -y
apt remove postfix dovecot* --purge -y
apt remove php8.0-fpm --purge -y
apt remove bind9 --purge -y
apt remove postgrey --purge -y
apt remove apache2 --purge -y
apt remove spampd --purge -y
apt remove --purge nginx* -y
apt remove nsd --purge -y
rm -rf /usr/local/lib/roundcubemail
rm -rf /usr/local/lib/owncloud/
```
