### ISSUE TITLE
Remote Control of Security Features on Android when using Z-PUSH

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#607]
Hi there,

If I add my ActiveSync Account (Mail in a Box) on a Android Phone, the ActiveSync Server wants some Permissions and Security Features.

It looks like the attached screenshot. 

I think my box does not need to have the right for erasing my whole phone :D If somebody would hack the box, then he would be able to erase or acess my android phone? On my iPhone, this isnt a problem.

![android-09](https://cloud.githubusercontent.com/assets/12893462/11343422/49008218-920c-11e5-97d2-cc397449ba7f.png)

**Comment by JoshData** [comment]
Yeah, I don't know why this is happening.

**Comment by aspdye** [comment]
Can we ask somebody at Z-Push?

**Comment by yodax** [comment]
This is a feature that is part of the the ActiveSync protocol, it supports device management. That is why Android is advising you about the possibility of a remote wipe. 

Wiping the device is only possible on MIAB when you have access to the command line. Thus an attacker would have gotten root access to the MIAB and you would already have a serious breach. Personally it would be more worrying to me that an attacker gained root, than it would be that they could remote wipe.

If you wan't to prevent this, you will have to use IMAP. Because even if you remove the functionality from z-push the attacker with root access can put it back :smile: since the device already trusts the remote server
