### ISSUE TITLE
fail2ban could protect POP3, SMTP too

### ISSUE THREAD

**Issue by gellenburg** [mail-in-a-box/mailinabox#629]
Looks like fail2ban is only configured for ssh?

Any way of expanding this to IMAP, POP3, and SMTP servers as well?

My "box" was sending out SPAM today, and from the logs it looks like my password was cracked for my main account. The spammers had access my mailbox via IMAP to retrieve a list of all email from-addresses in my Inbox, and then proceeded to use my SMTP server to send SPAM to those addresses.

A quick check of /var/log/fail2ban.log* shows only entries for SSH are actually getting "banned".

**Comment by MeltedLux** [comment]
Yep looks like just imap is protected see: https://github.com/mail-in-a-box/mailinabox/blob/master/conf/fail2ban/jail.local#L21

**Comment by bronson** [comment]
Just noticed, munin agrees: 

![screen shot 2015-12-22 at 3 59 57 pm](https://cloud.githubusercontent.com/assets/1776/11968820/1c9b7780-a8c5-11e5-867c-1579c5363246.png)

**Comment by bronson** [comment]
@gellenburg did you use an easy to guess password?  Or did they sniff it somewhere else?  Even without fail2ban, hopefully your admin password would take years of 100mbit traffic to guess.  Just curious.

(When I had the misfortune of running shared hosting at dreamhost, it didn't matter how strong a password you used...  Spammers would find an easy security hole on someone else's site, use a root vuln to take over the machine, then insert spam into the content of all the sites on that machine.  Happened to me twice.   So, if you're on a VPS, maybe it wasn't even your fault.)

**Comment by gellenburg** [comment]
Doesn't really matter my password complexity. Without fail2ban 
effectively /banning/ the attackers' /failed/ login attempts, they could 
have enumerated through all permutations and combinations. My password 
certainly could have been stronger (it is now!) but if fail2ban were 
configured to look for failed logins for IMAP and SMTP (as well as 
/admin, RoundCube and OwnCloud) and take action, then folks running MIAB 
would be better protected.

Part of the problem - and I know I'm not alone here - is that typing 
significantly complex passwords on a mobile device to configure an 
account is a royal fscking pain in the ass. :-)

Not everyone who runs a MIAB instance is a Linux sysadmin or has a SIEM. 
Let alone a SOC. :-)

**Comment by bronson** [comment]
That's my point: it should take centuries at 100mbit full blast to find a decent password by iteration.  That said, end users are notorious for choosing crappy passwords.  I agree, fail2ban is really important.

Currently:

- ssh: covered now
- imap: covered now
- pop: needed
- submission (port 587): needed.
- roundcube auth:  needed.  `/etc/fail2ban/filter.d/roundcube-auth.conf` exists, wonder if it can be used.
- admin interface: needed.  I don't see `daemon.py` logging either attempted or failed auths so this will require some python code as well as fail2ban.
- munin interface: needed.  it might be easier to make munin accept the admin interface's cookie rather than having fail2ban wach for auth basic fails in nginx/access.log.  Either way, this doesn't look real easy.

Did I miss anything?

**Comment by anoma** [comment]
I have been keen to start a group here looking specifically at FAIL2BAN enhancements for MIAB. I have submitted a few light cleanup PRs and a couple of trivial enhancement PRs but my constant worry is that for something this serious we need more eyes on it and more live test platforms.

For example other stuff for consideration:

recidived - a second PR to drop to 5 from 10
ufw traps - block obvious port scanners
nginx 404 traps - block obvious security scanners
proper reporting

IMHO we need a way to treat this as a sub project rather than a bunch of disjointed tickets.

**Comment by bronson** [comment]
That sounds excellent, I'd participate.

But where?   Seems like it's a choice between github forks+PRs or the forum...  Downside to forks+PRs is then you end up with a zillion branches that all have a few commits by a single person.  As you say, disjoint.  But the forum seems even worse.

Maybe create a harder-box branch with a few collaborators?  Solidify patches there, then push them back upstream.

**Comment by andysaini** [comment]
seconded, imperative feature!

**Comment by anoma** [comment]
How about this. We informally work here via PR's and use nick highlights to inform everyone there is something to test.

In place of a proper beta program the PRs can have extremely safe trigger counts. This is how I done the recidived PR where it only kicks in after 30 failed SSH logins in a day.

If we follow the same approach "we" can play with much tighter numbers here and as time passes we can drop the numbers to general MIAB users via subsequent PRs.

It is not ideal but I am not excited to start forking all over the place for what will be small amounts of code tested slowly over a long period of time.

**Comment by bronson** [comment]
@anoma sounds good to me.  I have a few other MIAB tasks to do before I can look at fail2ban but I'm eager to try some patches.

**Comment by JoshData** [comment]
This is all really important. I'd really appreciate it if any of you have time to submit PRs to get fail2ban to cover all of the services where a user logs in.

**Comment by bronson** [comment]
@JoshData hypothetically, do you have an idea on how to test fail2ban?  It would be nice to approach this systematically... but that might be more effort than it's worth.

**Comment by anoma** [comment]
Once we decide where and how we are doing this I have a new proposal to discussl:

Once an IP triggers a jail, block it from all ports not just a select few.

**Comment by anoma** [comment]
As per my last post I have been running 404, multiple ufw and a few other prototype jails since December but I have not placed any PRs as my single server is not a viable test group.

I can see fail2ban tickets here are getting more interest than ever before but we all seem to be doing our own thing.

Any thoughts how we can team up? Perhaps we could just have one release cycle where we focus on all things security including fail2ban.

**Comment by JoshData** [comment]
Looks like we took care of this in #798.
