### ISSUE TITLE
RFC fail2ban ban ip rather than port

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#684]
This is a request for comment on a potential PR.

Currently our fail2ban design blocks specific ports for offenders i.e. if someone trips the ssh jail trigger they are blocked from ssh but nothing else.

I propose that we change the defaults so that that offenders are completely blocked from all services.

**Comment by kdfreeheart** [comment]
I share your passion for security, but I frequently deal with real-world scenarios where these rules would prevent me from doing my job.

My first counter to this PR is the fact that most mobile apps attempt to "auto-configure". 

SMTP settings might be on ports 25 or 587 per RFC. If they're encrypted, there might be another set of ports, per different RFC. And some people/companies run servers on non-standard ports because they think that gives them more security. Mobile apps will try *all* of those options before telling their users that they fail at doing email, and most of the apps that fail to deliver messages present their users with two options.

"Cancel" and "Retry".

Meanwhile, I'm the administrator responsible for seamlessly migrating that user's email to my company's servers, which run MiaB.

Most of those failed connections were *me*, playing around with an App that I'm not familiar with, but because the fail2ban rules were IP based and not activity-based, I can't SSH into the box and flush the firewall rules that I need to remove before I can send a message to my boss about why "the customer's problem hasn't been resolved yet".

**Comment by anoma** [comment]
A fair point of view. Let me make some observations:

* For most people the time when they will trigger traps will be in the initial setup phase. We should ideally cater directly for this rather than lessen security for the rest of time  i.e. a few days of initial install  versus hopefully years of running.
* If you have a userbase who are constantly hitting the server due to a bad config in a way that triggers a trap then IMO you four options, refine the fail2ban settings so that your users don’t get trapped, turn fail2ban off, fix your clients or we fix MIAB so that it caters for client defaults better.
* Certainly the system should not be so sensitive that it trigger on simple user PEBCAK.
* We discussed having two configs shipped, a super safe version that only is triggered on extreme cases and a secure one that assumes most bad access is potential abuse. We should probably extend this to a third option which is actually just turn fail2ban off.
* We should provide a means to add a whitelist of IPs via the GUI and educate users to the implications of using the more sensitive config if they don’t.

Fundamentally I believe it is far more likely that most MIAB  installs are relatively static and would benefit from the increased security but we do need a way to beta test this stuff. Me running it for months is the best I can do alone but it still falls far short.

One thing that might be possible is to implement this where the ban action is actually just an email saying “I would have banned this, please post feedback here if this would have been bad”.

**Comment by JoshData** [comment]
There are only a small number of services running. So if you get blocked on one port, having 5 more to try shouldn't be the difference between the attacker getting in or not.

**Comment by anoma** [comment]
For me at least once you have identified someone as being an attacker fundamentally they should not be allowed access to attack any other services. This follows the principle of security in depth and decreases the risk of attack escalation.

The one argument against this is a legitimate user causing a false positive but I would suggest this is a failing in the jails and exceptions rather than the ban action.

**Comment by JoshData** [comment]
I realize now that this would make my testing harder. If when I test one port I get blocked from SSH, then I am very out of luck with getting things back to normal. So I am going to close this.
