### ISSUE TITLE
Error Provisioning TLS Certificate

### ISSUE THREAD

**Issue by mpr555** [mail-in-a-box/mailinabox#696]
Hi I am getting these emails daily

I am not sure if it working correctly.  I have no options to hit yes to agree.

This is in the email message body.

I'm going to provision a TLS certificate (formerly called a SSL certificate)
for you from Let's Encrypt (letsencrypt.org).

TLS certificates are cryptographic keys that ensure communication between
you and this box are secure when getting and sending mail and visiting
websites hosted on this box. Let's Encrypt is a free provider of TLS
certificates.

Please open this document in your web browser:

https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf

It is Let's Encrypt's terms of service agreement. If you agree, I can
provision that TLS certificate. If you don't agree, you will have an
opportunity to install your own TLS certificate from the Mail-in-a-Box
control panel.

Do you agree to the agreement? Type Y or N and press <ENTER>: 
You didn't agree. Quitting.

**Comment by wraithgar** [comment]
Was this closed because you figured out why the emails were happening? Can you share what fixed this?

**Comment by mpr555** [comment]
I made a bit of a mistake.  I didn't realise that you had to go into TLS on the system menu and follow the instructions for the free cert.  Once I had done that, it installed the certs.

Originally I wasn't sure where the emails were coming from.  I should of explored a little more to find this out before posting an issue.

Live and learn though I suppose.

Cheers

**Comment by EmperorEarth** [comment]
I get this email nightly, and it's getting very annoying.

I have a box at a custom url `mail.domain.tld`
With this box, I'm sending emails from:
```
foo@mail.domain.tld
foo@domain.tld
```

I have a valid cert for `mail.domain.tld` but not `domain.tld`
I'm planning to host `domain.tld` on a different VPS, and have no wishes to get a TLS cert for `www.domain.tld` nor one for `domain.tld`.

What can I do?

**Comment by dhpiggott** [comment]
TLS certs are not used only for web hosting, they are required for sending (and receiving) email too. So your MIAB _does_ require a cert for domain.tld.

If I've been following correctly, you have two ways of fulfilling that requirement:

You can: login to the MIAB control panel, go to System > TLS (SSL) Certificates and then click the relevant buttons to accept the Let's Encrypt agreement (if you do agree with it!). The box will then procure the required domain.tld cert overnight when it next runs checks. You can also click to trigger it from the control panel.

Or: purchase a cert for domain.tld from the same provider that you got your mail.domain.tld cert from, and install it on the box in the same way as you did the mail.domain.tld cert.

**Comment by JoshData** [comment]
> TLS certs are not used only for web hosting, they are required for sending (and receiving) email too.

Quick correction: Technically, no signed certificate is required. Everything will work fine (and be virtually as secure, at a protocol level) if the user doesn't take any step to install a signed cert, because the box starts off with a self-signed certificate (and at a protocol level that's basically good enough). But at a practical level, if you want to avoid security warnings in your mail/contacts/calendar client and in your web browser (for webmail), then a real (signed) certificate is required for the box's hostname (only), in this case  `mail.domain.tld` (what the setup guide recommends as `box.domain.tld`). Additionally, if you want mail client autoconfiguration to work, which relies on web, then you (probably) need a signed certificate for every domain that hosts a mail account. And of course if you want to use the static web hosting on any domain, you'll need a certificate for that domain. (But if the domain is going to be hosted elsewhere, autoconfiguration and static web don't apply.)

> I'm planning to host domain.tld on a different VPS, and have no wishes to get a TLS cert for www.domain.tld nor one for domain.tld.

The warning email will go away just as soon as your DNS is configured to actually host those domains elsewhere. It's smart!

But since certificates are now free, it's fastest to just procure one, as @dhpiggott says. (My commit above to fix this issue replaces the text of the email you're getting with instructions for going to the control panel.)

**Comment by dhpiggott** [comment]
> Quick correction: Technically, no signed certificate is required.

Thanks for the correction. I was actually aware of all that, but your explanation will of course benefit others. I'm often accused of being too verbose (in written and spoken communication). Sometimes in an attempt to correct this I go to far the other way. What I meant was that @EmperorEarth's MIAB "wants" to get a trusted certificate (in order to prevent the issues of warnings etc. that you expanded on). In my attempt at brevity I elided to clarify this.

As a pedant though I note that I didn't actually say that MIAB requires a _trusted_ ("signed") cert (though I did pretty much imply it).

**Comment by JoshData** [comment]
No worries, and, yes, I just want it to be correct for anyone that might read it in the future. :)

**Comment by EmperorEarth** [comment]
@dhpiggott No worries. We're all learning new things and benefiting from @JoshData and crew's extensive work and expertise in this area.

@JoshData, it is as you say: I set up my mailinabox for `mail.domain.tld`, and that is my only web interface for the box. As I'm swamped with other projects right now, the `domain.tld` project will have to wait.

I would understand if the process to turn off this notification required re-entering the credentials and extra confirmation dialogs-- part of your project's purpose is to make self-hosted email servers more accessible and by consequence more idiot-proof. It's just frustrating to not be able to reliably turn off this inapplicable warning. Indeed, the entire email notification customizations deserve some attention!

Aside that, I applaud your rapid response. It's very comforting to know that this (real-life) dependency has passionate and present leadership.
