### ISSUE TITLE
nginx OCSP stapling does not work

### ISSUE THREAD

**Issue by 0xFelix** [mail-in-a-box/mailinabox#705]
In `/var/log/nginx/error.log` several of these messages appear:

`2016/02/09 22:20:21 [error] 2417#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: gv.symcd.com`

Examining the nginx config reveals that we never set `ssl_trusted_certificate` though it is needed for OCSP stapling, even the comment in nginx-ssl.conf says so.

https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-ssl.conf#L68

It seems that including the root and intermediate certificates in the `ssl_certificate` is not sufficient.

Perhaps I can work on a PR in the next days if you want.

**Comment by JoshData** [comment]
I'm not exactly sure what's going on. On my box, [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=box.occams.info) and openssl (below) seem to report that OCSP is working:

    $ openssl s_client -connect box.occams.info:443 -status 
    ...
    OCSP Response Data:
        OCSP Response Status: successful (0x0)

Maybe because Lets Encrypt is cross-signed something is working by accident for me.

Can you test your box this way?

It also might be difficult to automatically determine the trust path, though, so fixing this (if it needs to be fixed) might not be straightforward.

**Comment by JoshData** [comment]
(It could also be that your TLS certificate provider doesn't support OCSP?)

**Comment by 0xFelix** [comment]
I get this on my server:

```
CONNECTED(00000003)
OCSP response: no response sent
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s: ... -snip- ...
   i:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
 1 s:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
---
```

As you can probably see, I'm using RapidSSL and according to [this](https://www.rapidssl.com/learn-ssl/guides/ocsp-stapling.pdf) they support OCSP.

**Comment by 0xFelix** [comment]
Setting `ssl_trusted_certificate /home/user-data/ssl/ssl_certificate.pem;` for the main domain seems to fix the issue?

```
CONNECTED(00000003)
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=19:self signed certificate in certificate chain
verify return:0
OCSP response:
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
```

**Comment by 0xFelix** [comment]
Got the same behavior on my other domains too, they use StartSSL certs.

I guess not using `ssl_trusted_certificate` does not always work?
@JoshData How does your config with LetsEncrypt look like?!

**Comment by JoshData** [comment]
My config is the same as everyone else's, but I've got a Let's Encrypt cert and, I think, its intermediate cert is in the ssl_certificate file.

**Comment by 0xFelix** [comment]
I tested `ssl_certificate` with domain+intermediate certs and domain+intermediate+root certs.
OCSP only works for me when `ssl_trusted_certificate` is set.

Do you only have Let's Encrypt certs? I'm surprised your nginx OCSP stapling works even though you never set `ssl_trusted_certificate` and despite the documentation explicitly states you have to set it.

**Comment by yodax** [comment]
I was going to look into this because I saw the same errors in my log. 

```
OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: ocsp.startssl.com
```

I use start SSL. I saw however that the last message was on the 25th. Then I ran:

```
zcat -f -- error* | grep -i "OCSP.*unable to get local issuer certificate" | awk '{print $1}' | sort | uniq > ~/dates_with_ocsp_errors.lig
```

This gave me a list of dates where the system experienced ocsp errors. As far as the log goes everyday there is an error, but starting from January the 28th it isn't every day. It is more around every 2 to 3 days.

When I verify the response now all is okay:

```
OCSP response: 
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: B390A7D8C9AF4ECD613C9F7CAD5D7F41FD6930EA
    Produced At: Feb 25 16:28:51 2016 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: A5E2344EF5763A9CE2F31E9B9807B0075727A5F9
      Issuer Key Hash: B390A7D8C9AF4ECD613C9F7CAD5D7F41FD6930EA
      Serial Number: D40AEC190FB5DDA54175967BE136B7DE
    Cert Status: good
    This Update: Feb 25 16:28:51 2016 GMT
    Next Update: Feb 29 16:28:51 2016 GMT
```

The response was fetched on the 25th. The certificate chain is in the server certificate. I find it weird that it sometimes works and sometimes it doesn't. You would think it either validates or it doesn't. 

Everything you can find on the net indeed mentions that you should set:

```
ssl_stapling_verify on;
ssl_trusted_certificate ....;
```

I can't find any reference on disabling the verify; the only risk I see is a dns mitm attack on the ocsp service but all that would do is show an error on the client when he verifies the ocsp response against the cert. However I am not an expert on these matters.

**Comment by yodax** [comment]
I can't explain why it is working now. The correct way of doing it (at least with my limit understanding) seems to be:

- When the user pastes the intermediate chain with its root save it to a file next to the domain cert
- Reference the file in the domain specific section of the nginx config using the ssl_trusted_certificate directive

If the user doesn't paste the chain we set disable ssl_stapling_verify off or disable stapling altogether.

Does that make sense? (Or am I just rambling :smiley:)
