### ISSUE TITLE
Error: too many hops (in reply to end of DATA command)

### ISSUE THREAD

**Issue by pryley** [mail-in-a-box/mailinabox#713]
I was getting undelivered mail with the error: `Error: too many hops (in reply to end of DATA command)
`

I tracked down the error to the postfix `mydestination` config (`/etc/postfix/main.cf`). For some reason the line had been commented out and replaced with `mydestination = localhost`

```
#mydestination = mymailserver.com, localhost.com, , localhost
mydestination = localhost
```

I fixed it by changing it to:

```
mydestination = $myhostname, localhost.$mydomain, localhost
```

I have no idea if/why it changed and I only just started getting reports of the undeliverable mail from a user today. Maybe this will help someone else.

**Comment by JoshData** [comment]
The original is correct. There must be something else on your system that is different/incorrect.

**Comment by pryley** [comment]
Ok well since you said it was correct, I've changed the postfix setting back to 
`mydestination = localhost`.

---

So the original problem was this:

```
This is the mail system at host spam.flamble.it.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<xxxx@vonschenk.me.uk>: host fcis.flamble.co.uk[185.66.112.46] said: 554 5.4.0
   Error: too many hops (in reply to end of DATA command)
Reporting-MTA: dns; spam.flamble.it
X-Postfix-Queue-ID: F2C8AFEE0B
X-Postfix-Sender: rfc822; xxxx@xxxxxxx.com
Arrival-Date: Mon, 15 Feb 2016 19:53:14 +0000 (GMT)
...
```


I got the fix from http://serverfault.com/questions/651974/postfix-too-many-hops-bounce-back#651977. After changing it and restarting the mail server, it seemed to work ok as the email was sent with no bouce-back...but a while later I got the following email.

```
This is the mail system at host spam.flamble.it.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 1 hour(s).
It will be retried until it is 3 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<xxxx@vonschenk.me.uk>: connect to fcis.flamble.co.uk[185.66.112.46]:25:
   Connection refused
Reporting-MTA: dns; spam.flamble.it
X-Postfix-Queue-ID: 15397FEDC3
X-Postfix-Sender: rfc822; xxxx@xxxxxxx.com
Arrival-Date: Mon, 15 Feb 2016 20:36:55 +0000 (GMT)

Final-Recipient: rfc822; xxxx@vonschenk.me.uk
Original-Recipient: rfc822;xxxx@vonschenk.me.uk
Action: delayed
Status: 4.4.1
Diagnostic-Code: X-Postfix; connect to fcis.flamble.co.uk[185.66.112.46]:25:
   Connection refused
Will-Retry-Until: Thu, 18 Feb 2016 20:36:55 +0000 (GMT)
Return-Path: <xxxx@xxxxxxx.com>
Received: from spam.flamble.it (localhost [127.0.0.1])
 by spam.flamble.it (Postfix) with ESMTP id 15397FEDC3
 for <xxxx@vonschenk.me.uk>; Mon, 15 Feb 2016 20:36:55 +0000 (GMT)
X-Virus-Scanned: by SpamTitan at flamble.it
X-Spam-Flag: NO
X-Spam-Score: -2.1
X-Spam-Level:
X-Spam-Status: No, score=-2.1 tagged_above=-999 required=5
 tests=[BAYES_00=-1.9, DKIM_SIGNED=0.1, DKIM_VALID=-0.1,
 DKIM_VALID_AU=-0.1, HTML_MESSAGE=0.001, SPF_HELO_PASS=-0.001,
 ST_P0F_Linux=-0.1] autolearn=ham
Authentication-Results: spam.flamble.it (amavisd-new);
 dkim=pass (2048-bit key) header.d=xxxxxxx.com
Received: from spam.flamble.it (localhost [127.0.0.1])
 by spam.flamble.it (Postfix) with ESMTP id 14D81FECEE
 for <xxxx@vonschenk.me.uk>; Mon, 15 Feb 2016 20:36:51 +0000 (GMT)
Received: from [IPv6:2605:e000:6141:7f00:f08e:324f:23b1:add4] (unknown [IPv6:2605:e000:6141:7f00:f08e:324f:23b1:add4])
 (using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
 (No client certificate requested)
 by geminimail.io (Postfix) with ESMTPSA id A6D2C14012A;
 Mon, 15 Feb 2016 16:12:29 -0500 (EST)
Authentication-Results: geminimail.io; dmarc=fail header.from=xxxxxxx.com
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=xxxxxxx.com;
 s=mail; t=1455570750;
 bh=Zm1exuixs/HNf8t3iADznzubdBTUCTqRgB6nMOymoHo=;
 h=Subject:From:In-Reply-To:Date:Cc:References:To:From;
 b=ZDkpRkBIfzIjcb5RN9JaVa3TEMFRgxhuWW06KIQEBR9YH201C3KIok/ZvsYKaS8/i
  5TmELJXIdYlzlvQ6mEwCtFibks2LY82DHi64G6fV66MZzSAra5VEQsZIMfeGy+62Vs
  66nZfCckjyCW6Fs6yMH6LiP/hlX/E7UNjH/wUum+equBSb65+ZRMAUbp2hwX1uUL7Z
  8kyRuPYX4djmfbqXLfEtnWAX7ME2ImJBCLfF9XSi5Siv8fSHUSbgF0EJp6W+CvrP/k
  IPQ2KPJejXyjgTOZHv9RUQ0KUqG3BvlyBEqCNGEVjRMemRlJEvSjKQfK2PMpU5neNo
  4DEnaBskMwgiw==
```

I used http://dkimvalidator.com/ to verify the DKIM and SPF settings and both pass.

Here is the SpamAssassin Score:

```
SpamAssassin Score: 0.111
Message is NOT marked as spam
Points breakdown: 
 0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was blocked.
                            See
                            http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                             for more information.
                            [URIs: xxxxxxx.com]
-0.0 SPF_HELO_PASS          SPF: HELO matches SPF record
 0.0 HTML_MESSAGE           BODY: HTML included in message
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily valid
 0.0 T_DKIM_INVALID         DKIM-Signature header exists but is not valid
```

So I'm not sure if the problem is with my mail server, or the recipient.

**Comment by dhpiggott** [comment]
I want to help here but I found it difficult to follow things due to the hostname and username redactions. Do you think you could you unredact some or otherwise make it clearer what's going on?

Just spelling out which string is which entity might help (e.g. "vonschenk.me.uk" = "my server", "fcis.flamble.co.uk" = "remote recipient's server", "my address on my MIAB" = "xxxx", "xxxxxxx.com" = "???" etc.).

**Comment by pryley** [comment]
Sure.

1. `geminimail.io` is my mail server
2. `xxx@xxxxxxx.com` is the user that is trying to send the message on my mail server
3. `xxxxxxx.com` is a domain that uses my mail server
4. The email is being sent to `xxxx@vonschenk.me.uk`

Does that help?

**Comment by dhpiggott** [comment]
Thanks, it does.

So knowing that the destination address is `xxxx@vonschenk.me.uk` I do an MX record lookup for `vonschenk.me.uk`:

```
david@ash ~ $ dig MX vonschenk.me.uk +short
0 spam.flamble.net.
10 mail.cluster.flamble.net.
```

OK, so that's why and what `spam.flamble.net` is.

Reviewing the headers it does seem that your MIAB successfully delivered the mail to `spam.flamble.net` which would at least _suggest_ there isn't an issue with your box. The rejection happens when `spam.flamble.net` tries to deliver to the ultimate destination, `fcis.flamble.co.uk`. Except that it's not actually a rejection, or at least it doesn't appear to be:

```
Diagnostic-Code: X-Postfix; connect to fcis.flamble.co.uk[185.66.112.46]:25:
   Connection refused
```

On the surface it looks like a temporary issue with the destination `fcis.flamble.co.uk`, as I have no issue establishing a connection to it right now:

```
david@ash ~ $ telnet fcis.flamble.co.uk 25
Trying 185.66.112.46...
Connected to fc.flamble.co.uk.
Escape character is '^]'.
220 fc.flamble.it FirstClass ESMTP Mail Server v11.1 ready
```

If I've not misinterpreted anything it would seem reasonable to hope that `spam.flamble.co.uk` will get around to retrying the delivery to `fcis.flamble.co.uk` soon at which point the mail will get delivered (if it hasn't done so already).

You might consider emailing postmaster@flamble.co.uk and sharing a link to this issue with them in case they can shed any further light on it too.

**Comment by pryley** [comment]
@dhpiggott Your reply was very educational. I really appreciate it. Thank you!

**Comment by dhpiggott** [comment]
Great!

In case you or anyone else was/is wondering about the `mydestination = localhost` thing, the reason it has to be set to just localhost is because MIAB uses Postfix's "virtual domain hosting" (http://www.postfix.org/VIRTUAL_README.html) support. Per the documentation for `mydestination` at http://www.postfix.org/postconf.5.html#mydestination:
> Do not specify the names of virtual domains - those domains are specified elsewhere. See VIRTUAL_README for more information.

(in the context of MIAB every domain is a virtual domain).
