### ISSUE TITLE
Drown Attack

### ISSUE THREAD

**Issue by laupkram** [mail-in-a-box/mailinabox#745]
A new TLS vulnerability appeared.

https://drownattack.com/

Will it affect Mail-in-a-Box?

**Comment by MeltedLux** [comment]
nope

**Comment by JoshData** [comment]
To clarify:

* If Mail-in-a-Box is your only web/mail server, you are not affected. (Because Mail-in-a-Box does not offer SSLv2.)

Your Mail-in-a-Box would be affected if:

* You run other web/mail servers, and
* You copied a TLS private key from one server to another, and
* One of those other servers offer SSLv2 connections.

**Comment by laupkram** [comment]
Ok thank you Josh For clarificiations :) Closing this issue now :)
