### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by chamunks** [mail-in-a-box/mailinabox#843]
I would LOVE to run something like this in Docker.  The contender I've been mulling over is https://poste.io but that has me weary because I can't see the whole process and closed source stuff etc.

If I'm going to bother with hosting my own Email server the compromise of having to deal with its maintenance should come with assured transparency.  I'm fine with the idea of this but only if it can be reasonably simple to deploy and transportable in case my hosting provider decides to be untrustworthy all of a sudden or other simply logistical issues.

putting this thing into a `docker run` command would be lovely.

**Comment by JoshData** [comment]
Do an issue search for all of the many frustrated threads we've had about this. :) it turns out to be actually really hard to build a docker image for Mail-in-a-Box and despite many many hours being put into it, no one has figured out how to do it completely.

**Comment by chamunks** [comment]
There does seem to be quite a few moving parts.  I was going to work on it in the past but then realised it was a bit of a rabbit hole project.  That said I do think that it would be ideal to get something done here.  As it would ensure that everything that can be is as secure as it can possibly be.  Certain things like Fail2Ban and stuff like that wouldn't easily integrate for sure seeing as one container really shouldn't be able to see another container easily.

**Comment by joelchen** [comment]
Perhaps a good alternative: https://github.com/tomav/docker-mailserver

**Comment by boredomdenied** [comment]
Well. I've got it installed in docker. Running it through the rounds. Will make a post on forum this weekend when it's all cleaned up and ready.

**Comment by chamunks** [comment]
The only reason I was kind of hoping it'd be in the official repository is for the public maintenance from the community room miab

**Comment by g19fanatic** [comment]
@boredomdenied   
> Finally got everything appearing to work. I'm going to start from scratch, make volumes, and test out moving to another vps. If all seems well will **_create a docker image, github repo & forum post_**

Any chance these were completed? If so, would you be able to link them?

**Comment by webeindustry** [comment]
No MIAB is very difficult to dockerize. My last assessment was that it would be easier to build a similar architecture from the ground up starting with docker in mind than to dockerize MIAB.

**Comment by chamunks** [comment]
To be honest my main interest in docker in this use case is I have a VPS that I've been renting forever and occasionally beat it up too much testing various things.  If something as awesome as MIAB could be set up so it's a bit easier to migrate or even store some of the stuff in a git repository I'd be all over this.

**Comment by haraldkoch** [comment]
As posted in the other docker issue: https://github.com/tomav/docker-mailserver is quite active.

**Comment by cyraid** [comment]
> As posted in the other docker issue: https://github.com/tomav/docker-mailserver is quite active.

So you're saying they did the 'super hard things' others are talking about here, but on that github? Is it feature comparable? Do they use the same services?

**Comment by JoshData** [comment]
I blocked @cyraid for 30 days for their disparaging sarcasm.

**Comment by Leopere** [comment]
I'm sorry you're getting pooped on for this stuff @joshdata that was not my intent when I'd authored this in 2016 I do still really wish that you would be able to shuffle this over to Docker because it could really solve a lot when it comes to migration to newer OS releases but the shift might inadvertently open MIAB up to new unpredictable security concerns in the process so I understand.   There are more than enough options that can scale and be dockerized but as for a system like this which is basically an all-in-one solution to get you off the ground quickly in a scenario that otherwise you would beholden to a CPanel or WHM system which feels kind of kludgey I get sticking to this format.  This setup is currently handling a few hundred DNS records on my main domain and at least 10 websites as well and it seems to be consistently solid.  I do however wish it was easier to find a reliably good IP address to use. I had landed on Contabo and that works for most cloud email but ProtonMail hates me and wont even pick up the phone and outlook dumps 100% of my stuff to spam.
