### ISSUE TITLE
Add link to upgrade instruction

### ISSUE THREAD

**Issue by ponychicken** [mail-in-a-box/mailinabox#865]
(in status_checks.py:L767) The reference to mailinabox.email should be a real link. On a tangential note, I think it would be wise to seperate the strings and the logic in this file, so that the python file only returns a json of the status codes and that is being rendered then in the browser.

**Comment by JoshData** [comment]
The script can also be run-standalone from the command line, so it needs to be able to output plain text (not HTML) _and_ the strings need to be present in the script so that they can be rendered for console output too.

Making it a link would be a lot of effort for a relatively small benefit at the moment.
