### ISSUE TITLE
+tag addresses alternate delimiter

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#877]
On three separate occasions recently I have hit issue with using the +tag addresses.

Unfortunately some website use bad email validity checks that reject the `+` symbol as not allowed (when obviously it should be).

Given that we cannot fix the internet could we allow alternate delimiter options?

**Comment by guyzmo** [comment]
it's possible to configure postfix to use an alternate delimiter, and I'm thinking myself of using `-` instead of `+`. Google for `postfix` and `recipient_delimiter` and you'll find your grail — beware that upon upgrading MIAB this setting might get overwritten, though.

But what's making me cautious about that, is that `+` still is a standard and some programs might rely on it, and not having it available might make some mails end up in `/dev/null`. So it's quite a tough situation, either you're going against good usage or you're getting fscked up by others who use a badly written regex instead of a proper email parsing lib.

Anyway, it's not gonna change in MIAB.

**Comment by anoma** [comment]
For reference the config example above is taken from the Postfix manual and not a DIY suggestion.

Are we sure it would break users with `-` delimiters. It was my understanding this case was handled but I have not tested it.

**Comment by yodax** [comment]
I thought the tags where an internet standard, it seems I was wrong. Or at least I can't find the rfc. Addresses can be just about anything so this isn't breaking anything. 

Good that you tested it. 

I'm generally annoyed when sites try to validate email address. They generally do a bad job. *.email is rarely accepted. Tags generally have the same problem. 

I would like this to be part of miab. @JoshData any comment on accepting a PR for this?

**Comment by JoshData** [comment]
There are different character requirements for user accounts because of Dovecot, which gets massively confused by some characters, as I recall. There was probably an old issue for this.

Separately from that, I really don't plan to make any changes about the delimiter. As I always say, I do not want the box to have any configuration options - for a variety of reasons, one of which is that I just don't have the time these days to review PRs that add functionality. I would rather see PRs that reduce the project's surface area, not add to it.

**Comment by anoma** [comment]
I am in two minds. I absolutely agree that each change increases the projects surface and I have no interest in making it more complicated for complications sake or an edge case just for me.

On the other hand the current `+` alias implementation only work sometimes. My tests here so far show that changing this to `+-` may make the feature work most of the time. Couple that with the fact it is documented in Postfix and Google reveals countless discussions on it I am still tempted to say it is a change worth investigating.

**Comment by yodax** [comment]
> On the other hand the current + alias implementation only work sometimes. My tests here so far show that changing this to +- may make the feature work most of the time.

For me that is an important argument. I don't use the tags as much as I would like to, because of this.

> As I always say, I do not want the box to have any configuration options

I see this as a change to the default configuration, not user configurable. 

> for a variety of reasons, one of which is that I just don't have the time these days to review PRs that add functionality.

This is an important argument, since this is a nice to have. 

I try to help in testing and reviewing PR's. I also understand that the weight of supporting it will be on your shoulders. (Even tough I try to help, you can never be sure for how long, people come and go)

**Comment by guyzmo** [comment]
My opinion on this is that it's a postfix matter, and the `+` default should be kept, even if some users (including me) might want to upgrade to `+-`, that should be kept as a local change within postfix not a configuration token within MIAB.

Maybe a good way forward would be to embrace such default changes using git merges when upgrading MIAB (or we could use an equilavent to `rc.local` to make changes to some config files, for advanced users that know what they're doing).

-----

That said, I'm actually a heavy user of the `+` part, as I'm using it along with notmuch to automatically generate tags. And that's true many sites use poorly written Regex (instead of proper protocol-based validation), though I find that there are more and more sites that are accepting it, when compared to a few years ago. What's fun is that I found many spambots that parses my mail addresses wrong and are sending me spams to `lasttag@domain.tld` instead of `user+tag1+lasttag@domain.tld` which is a good way to fight spam ☺ (i.e.: make spam@domain.tld a blackhole address, and all your publicly visible mails `user+spam@domain.tld`)

So, for notmuch, I have written a rule that generates tags out of the + parts (like `user+tag1+tag2+tag3@domain.tld` is being parsed and indexed with `tag1`, `tag2`, `tag3` tags). 

----

Having MIAB refusing to create mails containing `+` sign should be a good thing, as using it within mails will get the common user a UX nightmare going on all those stupid websites, and users should be encouraged in proper usage of the `+` delimiter.

Though, changing the default delimiter to `+-` should be of very little harm, because you can still build addresses containing `-` and (even if I did not check) I'm pretty sure that the registered address will have precedence over the `-` delimiter.

----

> >  for a variety of reasons, one of which is that I just don't have the time these days to review PRs that add functionality.
> This is an important argument, since this is a nice to have.
> I try to help in testing and reviewing PR's. I also understand that the weight of supporting it will be on your shoulders. (Even tough I try to help, you can never be sure for how long, people come and go) 

I'm also there to help, and I'll be around for as long as I'm an user of the project, which I chose principally because there's a lot of activity and contributions. So, don't hesitate to ping me for help!

**Comment by JoshData** [comment]
For the reasons discussed, I'm going to say no. I will add that, as I usually say, I am generally not interested in adding more features. There is enough work in just making the existing features work properly. Thanks for the good discussion all.

**Comment by anoma** [comment]
I have decided this is a must have feature for me since without it the existing alias feature is only sometimes useful. I will hack in a fix just for me.

**Comment by guyzmo** [comment]
it makes me think that maybe a wiki page with hacks/tips on how to customize MIAB could be a good idea. A bit like the [vim tips wiki](http://vim.wikia.com/wiki/Vim_Tips_Wiki)… I've also got a few workarounds of my own I did not advertise…

**Comment by lorrin** [comment]
@anoma I've come to the same conclusion too. I long ago decided `+` was rejected by too many sites and configured my mail server to accept `_` as well. Now those hundreds of existing accounts are preventing me from dropping in MIAB as a replacement. Can you share your hack? Happy to help with maintaining a wiki or a fork.

**Comment by lorrin** [comment]
FYI to anyone that is interested in tweaking this:

Recipient delimiter is required not only for Postfix, the mail transport agent (MTA), but also for Dovecot, the local delivery agent (LDA). Postfix supports supplying [multiple recipient_delimiter characters](http://www.postfix.org/postconf.5.html#recipient_delimiter), but Dovecot has not released such support. (The [enhancement was merged](https://github.com/dovecot/core/pull/4), for the 2.3 release, but as of 18.04 LTS, Ubuntu is [still on Dovecot 2.2](https://packages.ubuntu.com/search?keywords=dovecot-core&searchon=names&suite=bionic&section=all)). So I have settled for using _only_ `_` as my recipient delimiter, rather than either `+` or `_`. The commands to make the change are:

```bash
for f in /etc/dovecot/conf.d/15-lda.conf /etc/dovecot/conf.d/90-sieve.conf /etc/postfix/main.cf; do mailinabox/tools/editconf.py "$f" recipient_delimiter=_; done;
service dovecot restart
service postfix restart
```

**Comment by neuhaus** [comment]
I've used a (single) custom `recipient_delimiter` for subadressing (sometimes called plus addressing) for more than a decade. Works fine.

**Comment by lorrin** [comment]
MIAB 60 [upgraded to Dovecot 2.3](https://github.com/mail-in-a-box/mailinabox/blob/main/CHANGELOG.md#version-60-october-11-2022). It is now possible to use multiple recipient delimiters. For `+` and `_`, for example:
```
for f in /etc/dovecot/conf.d/15-lda.conf /etc/dovecot/conf.d/90-sieve.conf /etc/postfix/main.cf; do mailinabox/tools/editconf.py "$f" recipient_delimiter=+_; done;
service dovecot restart
service postfix restart
```
