### ISSUE TITLE
check_free_disk_space incorrectly calculates remaining free percentage

### ISSUE THREAD

**Issue by cmsirbu** [mail-in-a-box/mailinabox#932]
I've been getting some rather confused status messages lately when the free space started filling up on my box.

```
System -- Previously:
=====================
?  The disk has less than 10% space left.

System -- Currently:
====================
✓  The disk has less than 10% space left.
```

You can see something's fishy as the percentage is always 10%. In the "Previously" state it was around 18% and in the "Currently" state it is 31%.

I have found the problem and it's in the formula that calculates the message value only, the actual check is fine.

`disk_msg = "The disk has less than %s%% space left." % str(round(bytes_free/bytes_total/10 + .5)*10)`

I'm having trouble understanding the maths behind the formula above (which always yields a result of 10), but calculating a percentage is normally done like this: `round((bytes_free/bytes_total*100.0))`

I'll submit a PR shortly to fix this.

**Comment by cmsirbu** [comment]
Actually I've streamlined the formatting without any additional conversions to str:

```
       if not rounded_values:
                disk_msg = "The disk has %.2f GB space remaining." % (bytes_free/1024.0/1024.0/1024.0)
        else:
                disk_msg = "The disk has less than %.0f%% space left." % (bytes_free/bytes_total*100.0)
```


After the changes, testing on my box:

```
./status_checks.py --show-changes

System -- Previously:
=====================
✓  The disk has less than 10% space left.

System -- Currently:
====================
✓  The disk has less than 31% space left.

./status_checks.py

✓  The disk has 4.30 GB space remaining.
```

**Comment by JoshData** [comment]
I think the point of that line is to round to the nearest 10%.

The status checks send nightly emails whenever anything changes, and it would be annoying to get an alert every night that the disk space changed from 8% to 9%, and then the next night from 9% to 8%, and so on. So for the purposes of the emails, it shouldn't give an exact percentage.

**Comment by cmsirbu** [comment]
OK, I get your point. The message will change from ok (more than 30%) to warning (15-30) to error (under 15) so then the message should reflect that as well, does that make sense?

**Comment by cmsirbu** [comment]
Or if we want to round to the upper 10% we can do this: `math.ceil(bytes_free/bytes_total*10.0)*10`

The it can say "The disk has less than 40% space left." for any value from 30.00000001 to 39.9999999 :)

PS If you're wondering why math.ceil instead of round, here's why:

```
>>> round(3.5)
4
>>> round(4.5)
4
>>> round(5.5)
6
>>> round(6.5)
6
```

**Comment by JoshData** [comment]
That makes sense!

_But_ the reason it's been confusing was that 10% could either show with a checkmark (ok) or a question mark (warning). When the symbol changes but the text doesn't, it's confusing.

We should make it so that the same text cannot appear both as a warning and as an error.

Your change would fix it between [the ok and warning threshold at 30%](https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L236). I think. Maybe not if it's exactly 30% though.

But the original confusing problem remains even if we correctly round to the nearest 10%. Now the confusing text will be 20%, if I'm thinking about it right, and at the warning-error threshold. At 14%, you'll see "X  The disk has less than 20% space left." (error). At 16% you'll see "?  The disk has less than 20% space left." (warning). Right?

The thing to do would probably be to have a special if block that matches [the error if block](https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L238).

**Comment by cmsirbu** [comment]
Agreed, the "less than 20%" would be "?" for 19-15% and "X" for under 15%.

The disconnect is in where the error threshold is at - we round to multiples of 10, but the threshold is at 15.

I see 2 solutions:

1. We keep warning at 30 and change error to 20. Do math.ceil for % calculation.
2. We keep thresholds as before, but change the logic of the messages. We don't calculate the % anymore and have static messages for when over 30, under 30 over 15, and under 15.

**Comment by cmsirbu** [comment]
@JoshData I'd like to close this before it gets buried under all of the other stuff - any thoughts/decision on the suggestions above?

**Comment by JoshData** [comment]
> We keep thresholds as before, but change the logic of the messages. We don't calculate the % anymore and have static messages for when over 30, under 30 over 15, and under 15.

That one makes sense to me.  Thanks.
