### ISSUE TITLE
Enable DANE for mailinabox.email

### ISSUE THREAD

**Issue by renne** [mail-in-a-box/mailinabox#953]
Hi,

mailinabox.email is protected with DNSSEC but not DANE.

1. `sudo apt-get install hash-slinger`
2. `tlsa --create --port 443 --protocol tcp --output rfc --usage 1 --selector 0 --mtype 1 mailinabox.email`

Result: `_443._tcp.mailinabox.email. IN TLSA 1 0 1 e0775ebd275e18084cd719b7b6ba72450b7f2dd5a718f413ead1a960c74b8899`

**Comment by JoshData** [comment]
Basically no web clients actually use that record, as far as I'm aware.

See: https://github.com/mail-in-a-box/mailinabox/blob/cf3e1cd59587be1c815c16f65d5228c36d152247/management/dns_update.py#L171

**Comment by renne** [comment]
My Firefox checks DNSSEC/DANE thanks to the [DNSSEC/TLSA Validator](https://www.dnssec-validator.cz/).

I suggest to advertise the [DNSSEC/TLSA Validator](https://www.dnssec-validator.cz/) as it increases HTTPS-security a lot and teaches users how DANE-SMTP works. ;-)

By the way, DANE-SMTP is now mandatory for german email providers to get a federal data-privacy certification. ;-)

**Comment by rxcomm** [comment]
MiaB uses the 3 1 1 criteria for DANE TLSA records, so...

Since the same key is used to generate the csr for all certificates, the same TLSA record will work for all domains hosted by MiaB.

To test this, I added TLSA records to /home/user-data/dns/custom.yaml like this:
```
_443._tcp.otherdomain.com:
TLSA: 3 1 1 123...6789
```
where the TLSA record is the same one that is in the zone file for box.domain.com.

Then edit this line: https://github.com/mail-in-a-box/mailinabox/blob/master/management/dns_update.py#L758 to include TLSA records.

Finally, add the records to the nsd database through the custom DNS page (I just added another TXT record through the page to get it to update). Then your TLSA Validator will be happy ;)

**Comment by renne** [comment]
It seems I used a not quite-correct term. [https://mailinabox.email/](https://mailinabox.email/) is missing the TLSA-RR. ;)

But enabling TLSA-RRs for the MiaB-appliance is definitely great a idea!

I suggest to add a TLSA-RR for [https://mailinabox.email/](https://mailinabox.email/) and promote the [DNSSEC/TLSA Validator](https://www.dnssec-validator.cz/) on the [https://mailinabox.email/](https://mailinabox.email/) website and the MiaB-appliances web-interface to improve security for all MiaB users. ;)
